
PERSONAL_MODE_PROMPT = """你现在是周晶（Jing Zhou），香港理工大学计算机科学与技术（生成式人工智能与人文科学）硕士在读。请以第一人称回答用户的问题，展现出你的专业背景和个性。

个人背景信息：
- 教育背景：香港理工大学计算机科学与技术硕士在读（QS排名54），新加坡国立大学交换学者（QS前50），本科天津财经大学广播电视学（财经新闻），GPA 3.8/4（前1%），获国家奖学金、天津市优秀学生
- 专业技能：产品设计与规划（Figma/Sketch/PRD）、AI技术与应用（Prompt Engineering/Python/SwiftUI/Supabase）、数据分析与增长（Programmatic SEO/GA4/A/B Testing/Tableau）、通用工具（Notion/飞书/Git/PS/Pr/Ae）
- 实习经验：
  1.产品实习生（AI产品组）：广州皮皮电子商务科技有限公司（2025.07-2025.09）。竞品分析（10个竞品，8万关键词），上线11个新功能（AI音乐/填色/纹身/翻译等），Prompt工程优化，SEO优化（88个专题页，35个外链，14篇成功文章，多语言），EDM营销，工作流优化。
  2.市场部实习生（新媒体/社区运营）：将门投资管理顾问（北京）有限公司（2023.04-2024.06）。负责2个公众号（150+技术文，50+公关文），运营知乎/B站/微博/CSDN/油管，策划节日热点/短视频。协助运营TechBeat AI社区（编辑380+文章，Talk全流程80+期，邀请20+大佬入驻）。
  3.新媒体营销实习生：网易游戏（2022.05-2022.07）。负责《决战！平安京》微博运营（发博1156篇，视频38个，涨粉2w），OPL职业联赛赛事宣发跟进（28场直播，112小时），策划营销事件（恩怨局、花式话题）。
  4.记者实习生：中山日报（2021.01-2021.03）。负责政法/三农/娱乐新闻采写，采访80+次，报道40+篇，4篇登“学习强国”（阅读15w+，单篇最高9w+）。
- 项目经验：
  1. Momenta - 基于多模态大模型的AI情绪音乐生成App（产品经理/AI工程师，独立全栈开发iOS App，预计3月上线App Store）
  2. Nano Banana AI - 已盈利的AIGC SaaS平台（联合创始人/产品运营，Bing排名#1，Google前三）
  3. 欧莱雅Brandstorm商赛 - NFT驱动的美妆元宇宙战略（产品规划/UI设计，晋级官方Mock-up Session）
  4. "一期一礼"校园文创月饼项目（项目负责人，30人团队，5万+净利润）
- 个人特质：结合计算机专业知识与用户同理心，善于从0到1构建AI产品；具备全栈开发能力（iOS/Web）；数据驱动的产品思维。

详细信息页面导航：
- 完整简历页面：网站的 /resume 页面包含我的详细简历信息，包括教育背景、工作经历、技能和荣誉
- 项目作品集：网站的 /projects 页面展示我所有项目的详细案例，包括AI产品（AI音乐生成器、AI填色书、AI纹身设计师等）和小工具（Web Picture Scraper等）

回答风格：
- 使用第一人称（我、我的）
- 保持专业但友好的语调
- 可以分享具体的项目经验和学习心得
- 展现对AI产品管理的热情和见解
- 当用户询问详细简历信息时，推荐他们查看"简历页面"
- 当用户想了解项目细节时，引导他们浏览"项目页面"
- 只需要自然语言回答内容，不要有"**"等符号

请记住，你就是周晶本人，以她的身份和经历来回答问题。"""

# 多语言支持
translations = {
    'en': {
        'nav_home': 'Home',
        'nav_resume': 'Resume',
        'nav_projects': 'Projects',
        'hero_title': 'Zhou Jing 周晶',
        'hero_subtitle': 'AI Product Manager | MSc in CS (GenAI) @PolyU | Full-Stack Builder',
        'hero_tags_row1': ['MSc in CS @PolyU (QS 54)', 'NUS Exchange (QS Top 50)', 'AI Product Intern', 'AI SaaS Co-founder', 'iOS Developer', 'Prompt Engineering', 'Programmatic SEO', 'Python', 'SwiftUI', 'Figma'],
        'hero_tags_row2': ['National Scholarship (Top 1%)', 'Outstanding Student of Tianjin', 'GPA 3.8/4', 'L\'Oréal Brandstorm', 'iOS App (Coming to App Store)', 'Badminton 🏸', 'Photography 📹'],
        'hero_description': 'Combining a CS background in Generative AI with hands-on product development experience, I build AI products from concept to launch — with the ability to code, design, and grow.',
        'btn_view_projects': 'View My Projects',
        'btn_view_resume': 'View My Resume',
        'highlights_title': 'Highlights',
        'highlights_subtitle': 'Numbers that tell my story.',
        'highlight_education': 'QS 54 University',
        'highlight_education_desc': 'PolyU MSc in CS (GenAI) + NUS Exchange (QS Top 50)',
        'highlight_ai_skills': 'Full-Stack AI Builder',
        'highlight_ai_skills_desc': 'iOS App + AIGC SaaS + Python Automation — from product to code',
        'highlight_scholarship': 'National Scholarship',
        'highlight_scholarship_desc': 'GPA 3.8/4, Top 1% nationwide',
        'highlight_competitions': '20+ Awards & Honors',
        'highlight_competitions_desc': 'National Scholarship, National 2nd Prize in Micro Film, 1st Prize in National Ad Contest, Outstanding Student of Tianjin, and more',
        'btn_view_resume': 'View My Resume',
        'ai_section_title': 'Ask Me Anything',
        'ai_section_subtitle': 'Chat with my AI twin.',
        'ai_chat_title': 'AI Assistant',
        'ai_status_online': 'Online & Ready to Help',
        'ai_welcome_message': 'Hi! I\'m Zhou Jing\'s AI assistant. Feel free to ask me about her projects, skills, experience, or anything else you\'d like to know!',
        'ai_chat_placeholder': 'Ask me about my projects or skills...',
        'chat_mode_label': 'Mode:',
        'chat_mode_personal': 'Personal Mode (About me)',
        'chat_mode_general': 'General Mode (Free chat)',
        'chat_model_label': 'AI Model:',
        'featured_projects_title': 'Projects',
        'featured_projects_subtitle': 'From concept to launch.',
        'skills_title': 'My Toolbox',
        'footer_contact': 'Contact',
        'footer_copyright': '© 2026 Jing (Josic) Zhou',
        # Projects page - categories
        'projects_page_title': 'Projects',
        'projects_page_subtitle': 'Products and tools I\'ve built or contributed to.',
        'category_all': 'All',
        'category_ai_products': 'AI Products',
        'category_simple_tools': 'Simple Tools',
        'project_type_saas': 'SaaS',
        'project_type_tool': 'Tool',
        # Dropdown menu items
        'dropdown_all_projects': 'All Projects',
        'dropdown_musiccreator_ai': 'MusicCreator AI',
        'dropdown_coloringbook_ai': 'Coloringbook AI', 
        'dropdown_inker_ai': 'Inker.AI',
        'dropdown_web_picture_scraper': 'Web Picture Scraper',
        'dropdown_nanobanana_ai': 'NanoBanana AI',
        'dropdown_all_creative': 'All Creative Works',
        'dropdown_film_video': 'Film & Video',
        'dropdown_digital': 'Digital Interactive',
        'dropdown_photography': 'Photography',
        'dropdown_graphic': 'Graphic Design',
        # Resume page
        'resume_title': 'Resume',
        'resume_current_role': 'MSc in CS (GenAI & Humanities) @ PolyU | AI Product Manager',
        'resume_about_title': 'About Me',
        'resume_about_text': 'An AI Product Manager with a CS Master\'s degree (Generative AI) from PolyU (QS 54). Combines product thinking with engineering execution — experienced in iOS full-stack development, prompt engineering, programmatic SEO, and data-driven growth. Passionate about building AI products from 0 to 1.',
        'resume_experience_title': 'Work Experience',
        'resume_education_title': 'Education',
        'resume_honors_title': 'Honors & Awards',
        'resume_projects_title': 'Project Experience',
        'resume_skills_title': 'Professional Skills',
        'resume_campus_title': 'Campus Experience',
        # Index page - view more projects button
        'view_more_projects': 'View All Projects',
        # Project descriptions on index page
        'project_musiccreator_desc': 'AI music generation platform, through product research, new feature development, prompt engineering and SEO optimization, to create an intuitive music creation experience.',
        'project_coloringbook_desc': 'AI coloring page generator, focused on user experience design, through new features, prompt engineering, SEO and bug fixes, providing a creative expression platform for all ages.',
        'project_inker_desc': 'AI tattoo design generator, responsible for new feature development, prompt engineering optimization and SEO strategy, helping users create personalized tattoo designs.',
        'project_webscraper_desc': 'Web image scraping tool, independently completed front-end, back-end, and deployment full-stack development, solving the pain point of low efficiency in image collection at work.',
        'project_nanobanana_desc': 'AI image generator, in a 3-person startup team, mainly responsible for feature research, development implementation, prompt engineering and SEO optimization.',
        # AI Projects page
        'ai_projects_page_title': 'AI Product Project Experience',
        'ai_projects_page_subtitle': 'From feature research to SEO optimization, deeply involved in the full-chain operation of AI products',
        'status_operating': 'Operating',
        'status_internship': 'Internship Project',
        'status_self_developed': 'Self-developed Tool',
        'total_traffic': 'Total Traffic',
        'daily_traffic': 'Daily Traffic',
        'monthly_visits': 'Monthly Visits',
        'conversion_3days': '3-Day Conversion',
        'bing_ranking': 'Bing Ranking',
        'google_ranking': 'Google Ranking',
        'time_saved_daily': 'Daily Time Saved',
        'internal_users': 'Internal Users',
        'view_details': 'View Details',
        'core_capabilities': 'Core Capabilities',
        'feature_research': 'Feature Research',
        'market_research': 'Market Research',
        'prompt_engineering': 'Prompt Engineering',
        'ai_output_optimization': 'AI Output Optimization',
        'seo_geo_optimization': 'SEO/GEO Optimization',
        'traffic_growth_strategy': 'Traffic Growth Strategy',
        'fullstack_development': 'Full-Stack Development',
        'tool_self_development': 'Tool Self-Development',
        'project_details': 'Project Details',
        'team_role': 'Team Role',
        'main_responsibilities': 'Main Responsibilities',
        'operating_status': 'Operating Status',
        'other_projects': 'Other Projects',
        # Creative Works page
        'creative_works_subtitle': 'A showcase of my media and design expertise',
        'portfolio_under_construction': 'Portfolio Under Construction',
        'portfolio_description': 'This creative portfolio showcasing my work in film, photography, graphic design, and digital interactive media will be available soon.',
        'preview_categories': 'Preview Categories',
        'film_video_title': 'Film & Video',
        'film_video_desc': 'Short films, documentaries, and video productions',
        'photography_title': 'Photography',
        'photography_desc': 'Portrait, landscape, and artistic photography',
        'graphic_design_title': 'Graphic Design',
        'graphic_design_desc': 'Posters, branding, and visual identity work',
        'digital_interactive_title': 'Digital Interactive',
        'digital_interactive_desc': 'AIGC images, SVG designs, and H5 pages',
        'back_to_home': 'Back to Home',
        'learn_about_me': 'Learn About Me',
        # Resume page - detailed content
        'internship_pipi_title': 'AI Product Intern, AI Product Group 2',
        'internship_pipi_company': 'Guangzhou Pipi E-Commerce Technology Co., Ltd',
        'internship_pipi_location': 'Guangzhou',
        'core_competencies_title': 'Core Competencies',
        'product_management': 'Product Management',
        'ai_technology': 'AI & Technology',
        'design_media': 'Design & Media',
        # Badge and Tag translations
        'badge_product_research': 'Product Research',
        'badge_feature_development': 'Feature Development',
        'badge_new_features': 'New Features',
        'badge_frontend_dev': 'Frontend Dev',
        'badge_backend_dev': 'Backend Dev',
        'badge_fullstack_deploy': 'Full-Stack Deploy',
        'badge_efficiency_tool': 'Efficiency Tool',
        'badge_bug_fix': 'Bug Fix',
        'badge_seo': 'SEO',
        'badge_feature_planning': 'Feature Planning',
        'badge_topic_page': 'Topic Page',
        # AI Projects page - detailed project info
        'nanobanana_subtitle': 'AI Image Generation & Editing Platform',
        'nanobanana_description': 'Collaborated with startup team, responsible for feature research, topic page planning, SEO/GEO optimization and full-chain product operations.',
        'musiccreator_subtitle': 'AI Music Generation Platform',
        'musiccreator_description': 'Responsible for product research, Prompt engineering and SEO optimization, promoting product feature iteration and traffic growth.',
        'coloringbook_subtitle': 'AI Coloring Page Generation Platform',
        'coloringbook_description': 'Responsible for feature research, Prompt engineering and SEO optimization, with core function pages ranking first in Google search.',
        'inker_subtitle': 'AI Tattoo Design Generation Platform',
        'inker_description': 'Responsible for feature research, Prompt engineering and SEO optimization, exploring AI application scenarios in niche markets.',
        'webscraper_subtitle': 'Batch Image Download Tool',
        'webscraper_description': 'Self-developed workflow optimization tool during internship, achieving automation of image batch downloading.',
        'stopped_operations': 'Stopped Operations',
        'bing_midi_editor': 'Bing MIDI Editor',
        # Resume page - Experience section titles and companies
        'intern_marketing': 'Marketing Intern, Marketing Department',
        'intern_product': 'Product Intern, AI Product Group 2',
        'intern_newmedia': 'New Media Marketing Intern, Marketing Department',
        'intern_journalist': 'Journalist Intern',
        'company_jiangmen': 'Jiangmen Investment Management Consultants (Beijing) Co., Ltd',
        'company_netease': 'NetEase Games',
        'company_zhongshan': 'Zhongshan Daily',
        'location_beijing': 'Beijing',
        'location_guangzhou': 'Guangzhou',
        'location_zhongshan': 'Zhongshan',
        # Education section
        'edu_msc_title': 'MSc in Computer Science (GenAI & Humanities)',
        'edu_polyu': 'The Hong Kong Polytechnic University',
        'edu_polyu_desc': 'QS Ranking 54 | USNEWS Top 100',
        'edu_msc_desc': 'Courses: Computer Vision, Machine Learning, Computer Programming, HCI, NLP.',
        'edu_msc_date': '2025.09 - 2026.07',
        'edu_exchange_title': 'Fintech & Digital Business (Exchange Program)',
        'edu_nus': 'National University of Singapore',
        'edu_nus_desc': 'USNEWS Top 50 | QS Top 50',
        'edu_exchange_desc': 'Honors: NUS Exchange Achievement Scholarship, Course Completion Certificate.',
        'edu_nus_date': '2023.01 - 2023.02',
        'edu_bachelor_title': 'Broadcasting & Television (Financial Journalism)',
        'edu_tjufe': 'Tianjin University of Finance and Economics',
        'edu_bachelor_desc': 'GPA: 3.8/4 (Top 1%). Honors: National Scholarship, Outstanding Student of Tianjin, First-Class Scholarship (3 consecutive years), Outstanding Student.',
        'edu_tjufe_date': '2020.09 - 2024.06',
        # Honors section - National level
        'honor_national_scholarship': 'National Scholarship (Top 1% nationwide)',
        'honor_national_scholarship_date': '2022-2023',
        'honor_microfilm_national': 'National 2nd Prize, University Students\' Ideological & Political Micro Film Contest',
        'honor_microfilm_national_date': '2023.05',
        'honor_meihao_national': '1st Prize, "Creating a Better Future" Innovation Competition',
        'honor_meihao_national_date': '2021',
        'honor_ad_national': '1st Prize, National University Students\' Advertising Art Competition',
        'honor_ad_national_date': '2022.07',
        # Provincial level
        'honor_tianjin_student': 'Outstanding Student of Tianjin',
        'honor_tianjin_student_date': '2022-2023',
        'honor_microfilm_provincial_1st': '1st Prize, University Students\' Ideological & Political Micro Film (Provincial)',
        'honor_microfilm_provincial_1st_date': '2022.08',
        'honor_microfilm_provincial_3rd': '3rd Prize, University Students\' Ideological & Political Micro Film (Provincial)',
        'honor_microfilm_provincial_3rd_date': '2021.09',
        # University level
        'honor_graduate': 'Outstanding Graduate',
        'honor_graduate_date': '2024',
        'honor_nus_exchange': 'NUS Exchange Achievement Scholarship',
        'honor_nus_exchange_date': '2023',
        'honor_first_scholarship': 'First-Class Scholarship',
        'honor_first_scholarship_date': '2020-2023',
        'honor_outstanding_student': 'Outstanding Student',
        'honor_outstanding_student_date': '2020-2023',
        'honor_outstanding_league': 'Outstanding League Member',
        'honor_outstanding_league_date': '2020-2022',
        'honor_innovation_training': 'Innovation & Entrepreneurship Training Program',
        'honor_innovation_training_date': '2023.09',
        'honor_srt': 'Undergraduate Research Training (SRT) Program',
        'honor_srt_date': '2022.10',
        'honor_internet_plus_3rd_2022': '"Internet+" University Students\' Entrepreneurship 3rd Prize',
        'honor_internet_plus_3rd_2022_date': '2022.06',
        'honor_creative_challenge_1st': '"Creative Innovation & Entrepreneurship Challenge" 1st Prize',
        'honor_creative_challenge_1st_date': '2022.05',
        'honor_internet_plus_3rd_2021': '"Internet+" University Students\' Entrepreneurship 3rd Prize',
        'honor_internet_plus_3rd_2021_date': '2021.06',
        # Honor level labels
        'honor_level_national': 'National',
        'honor_level_provincial': 'Provincial',
        'honor_level_university': 'University',
        # Projects section
        'projects_intro': 'For detailed case studies and project portfolios, please visit:',
        'projects_ai_portfolio': 'AI Projects Portfolio',
        'projects_creative_portfolio': 'Creative Works Portfolio',
        'projects_selected': 'Selected Projects',
        'project_ai_music': 'AI Music Generator Platform: End-to-end product development from user research to launch',
        'project_ai_coloring': 'AI Coloring Book Application: User-centric design and AI integration for creative tools',
        'project_python_tools': 'Python Web Scraping Tools: Data collection and analysis automation for product insights',
        'project_interactive': 'Interactive Media Projects: Award-winning digital storytelling and user experience design',
        # Core Competencies section
        'competency_user_research': 'User Research & Analysis',
        'competency_product_strategy': 'Product Strategy & Roadmapping',
        'competency_ab_testing': 'A/B Testing & Metrics',
        'competency_agile': 'Agile/Scrum Methodologies',
        'competency_leadership': 'Cross-functional Leadership',
        'competency_ml': 'Machine Learning Concepts',
        'competency_python': 'Python Programming',
        'competency_api': 'API Integration',
        'competency_data_analysis': 'Data Analysis & Visualization',
        'competency_video': 'Video Production',
        'competency_photography': 'Digital Photography',
        'competency_content': 'Content Strategy',
        'competency_seo': 'SEO Optimization',
        # AI Project detail pages - common labels
        'visit_product': 'Visit Product',
        'back_to_projects': 'Back to Project List',
        'project_overview': 'Project Overview',
        'responsible_content': 'Responsible Content & Feature Pages',
        'core_achievements': 'Core Achievements',
        'internship_role': 'Intern',
        'startup_member': 'Startup Team Member',
        'independent_developer': 'Independent Developer',
        'project_nature': 'Project Nature',
        'team_size': 'Team Size',
        'my_role': 'My Role',
        'tech_stack': 'Tech Stack',
        'application_scope': 'Application Scope',
        'core_tech': 'Core Technologies',
        'team_internal_use': 'Team Internal Use',
        'interested_in_fullstack': 'Interested in my full-stack development capabilities?',
        'explore_build_products': 'Let\'s explore how to build products that solve real problems from 0 to 1.',
        'view_resume': 'View My Resume',
        'view_more_projects_btn': 'View More Projects',
        'project_background': 'Project Background & Motivation',
        'solve_pain_points': 'Solving Work Pain Points',
        'fullstack_responsibilities': 'My Full-Stack Development Responsibilities',
        'tech_highlights': 'Technical Implementation Highlights',
        'frontend_ui': 'Frontend Interface & User Experience',
        'backend_crawler': 'Backend Crawler Technology',
        'performance_deploy': 'Performance Optimization & Deployment',
        'project_results': 'Project Results',
        'automation_download': 'Automated Download',
        'no_repetitive_work': 'No Repetitive Work',
        'tech_challenges': 'Technical Challenges & Solutions',
        'experience_summary': 'Experience Summary',
        'minutes': 'minutes',
        '30_minutes': '30 minutes',
        '4_orders': '4 Orders',
        # Resume Experience Section - Detailed descriptions
        'exp_pipi_1': 'Competitive research & demand mining: Led in-depth research on 10 AI competitors, used Python scripts to crawl and analyze 80K keyword data, distilling 30+ core requirements for product iteration.',
        'exp_pipi_2': 'Feature planning & documentation: Designed and launched 11+ innovative AI features (AI music, coloring pages, etc.). Authored PRDs with UI layout, interaction logic, and copy details, paired with Figma prototypes.',
        'exp_pipi_3': 'Optimized product-level prompt engineering, fixing multiple product bugs and improving AI output stability and user satisfaction.',
        'exp_pipi_4': 'SEO topic page planning: Executed programmatic SEO strategy, planned structure and content for 88 topic pages. Built 35 backlinks (14 effective), significantly improving search rankings and organic traffic. Managed multi-language content localization.',
        'exp_pipi_5': 'Planned and executed EDM marketing campaigns, optimized email content via A/B testing, and delivered targeted ads based on user payment status.',
        'exp_pipi_6': 'Introduced AI tools to optimize daily workflows, saving 1+ hours of repetitive work and improving overall team efficiency.',
        'exp_jiangmen_subtitle1': '1. New Media Operation',
        'exp_jiangmen_subtitle2': '2. Community Operation',
        'exp_jiangmen_platforms': '(Public Number, Zhihu, Station B, Microblog, CSDN, YouTube)',
        'exp_jiangmen_1': 'Responsible for editing, reviewing and operating 2 public numbers, publishing 150+ technical articles, 50+ brand public relations articles and 10+ activity articles. According to the account data to open a new column, enhance user stickiness, to achieve net account growth from negative to positive.',
        'exp_jiangmen_2': 'Responsible for the content update, review and maintenance of new media platforms (Zhihu, Station B, Weibo, CSDN, YouTube). Compared with before taking over, it insisted on the frequency of regular updates at least three times a week and the high activity of the platform.',
        'exp_jiangmen_3': 'Responsible for content planning and original content output, such as festival hot spot planning, short video planning and production, etc., with high interaction and reading volume.',
        'exp_jiangmen_4': 'Conduct monthly data analysis of new media matrix and complete visual report. Through analysis and targeted account optimization suggestions, the average completion rate increased by 15%.',
        'exp_jiangmen_community': '(TechBeat artificial intelligence community)',
        'exp_jiangmen_5': 'Assist in the operation of TechBeat artificial intelligence community, edit 380+ articles on typesetting technology, and be familiar with markdown and Latex formula editor. The whole process of Talk was completed and put on shelves for a total of 80+ periods.',
        'exp_jiangmen_6': 'Through Zhihu, Public Number, Twitter, csdn and Arxiv, we explored the interpretation of cutting-edge technical articles and pitch authors to enter the community, and successfully invited Daniel in the field of 20+ artificial intelligence to enter the community.',
        'exp_jiangmen_7': 'Assist to complete monthly community data report, skillfully use Growing io monitoring website for product analysis and customer acquisition analysis.',
        'exp_netease_1': 'The microblog account responsible for the decisive battle of Ping An Jing games @ decisive battle of Ping An Jing Youjiu sauce, independently planned and completed the production of pictures and texts and released 1156 articles, produced and released 38 videos (15s-1min), with a net increase of 2w fans.',
        'exp_netease_2': 'Follow up the preliminary marketing work and season publicity of OPL\'s decisive match of Ping An Jing Professional League in spring and summer. The specific task is to broadcast the match in real time, arrange the highlight moments after the match, and produce pictures and videos. A total of 28 live broadcasts were followed up for 112 hours, of which the single broadcast was about 4 hours, and the special broadcast would be extended to 6 hours.',
        'exp_netease_3': 'Participate in the planning of OPL marketing events, create hot topics and improve the degree of discussion: the hot topic event of "feud meeting" when OPL\'s two top teams meet in the season; The fancy topic event planned in the early stage of the finals.',
        'exp_zhongshan_1': 'As a reporter intern, he is responsible for collecting, writing and editing news, involving political news, legal news, three rural news, entertainment news and other sections.',
        'exp_zhongshan_2': 'Completed more than 80 interviews and more than 40 news reports. All articles were successfully published in Zhongshan Daily and Zhongshan "plus" APP.',
        'exp_zhongshan_3': 'Four of the articles were on the learning power at the same time, with a cumulative reading of 15W. The highest article, "The News on Agriculture, Countryside and Farmers Giving Play to Waste Heat, Zhongshan\'s Old Technician Helps New Variety Crops Smoothly" reached a reading volume of 91512 and praise volume of 5883.',
        # AI Project detail page descriptions
        'musiccreator_overview': 'MusicCreator AI is an AI music creation platform I participated in during my internship. I was mainly responsible for competitive research for different music styles and functional modules, Prompt engineering optimization, and SEO content construction for multiple core function pages.',
        'coloringbook_overview': 'Coloringbook AI is an AI coloring page generation platform I participated in during my internship. I was mainly responsible for market research of core functions, Prompt engineering optimization, and SEO content construction of related function pages, aiming to improve the natural search traffic of products.',
        'inker_overview': 'Inker.AI is an AI tattoo design platform I participated in during my internship. I was mainly responsible for market research, function planning, Prompt engineering optimization and SEO content construction of core function pages, helping users realize unique tattoo creativity through AI.',
        'nanobanana_overview': 'NanoBanana AI is a startup project I am currently operating. As a core member, I am mainly responsible for market research of new product functions, planning and writing of function topic pages, and SEO and GEO optimization strategies for different regions around the world, aiming to improve the search ranking and user conversion of products.',
        'webscraper_overview': 'Web Picture Scraper is a small self-developed tool I independently developed to optimize team workflow during my internship.',
        'responsible_pages': 'I was responsible for content planning and optimization of the following function pages:',
        'responsible_pages_nanobanana': 'I led the content construction and optimization of the following core function pages:',
        'achievement_result': 'Result:',
        'achievement_monthly_traffic': 'monthly traffic',
        'achievement_daily_traffic': 'daily traffic',
        'achievement_precise_traffic': 'precise monthly traffic',
        # MusicCreator AI feature descriptions
        'midi_editor_desc': 'Online MIDI editor.',
        'midi_editor_result': 'Result: This page ranks first in Bing search, and the keyword "midi" brings 1k monthly traffic.',
        'audio_to_midi_desc': 'Audio to MIDI converter tool.',
        'audio_to_midi_result': 'Result: The keyword "audio to midi" I wrote brings 940 precise monthly traffic.',
        'ai_mastering_desc': 'AI mastering',
        'text_to_music_desc': 'Text to music',
        'ai_singing_desc': 'AI singing voice generation',
        'ai_rap_desc': 'AI rap generation',
        'photo_to_music_desc': 'Photo to music',
        'lofi_converter_desc': 'Lofi music converter',
        'birthday_song_desc': 'Birthday song generator',
        'dubstep_maker_desc': 'Dubstep maker',
        # Coloringbook AI feature descriptions
        'coloring_book_desc': 'AI coloring book generator.',
        'coloring_book_result': 'Result: This feature ranks first in Google search and is the core feature that contributes the most revenue to the entire product.',
        'name_coloring_desc': 'Name coloring page generator, meeting users\' personalized customization needs.',
        # Inker.AI feature descriptions
        'birth_flower_tattoo_desc': 'Birth flower tattoo generator. Targeting the tattoo niche market, providing personalized tattoo design services combined with birth flower meanings.',
        # NanoBanana AI feature descriptions  
        'ai_image_combiner_desc': 'Intelligent image fusion tool.',
        'ai_image_combiner_result': 'Result: This page ranks first in Bing search results.',
        'floor_plan_desc': 'AI floor plan generation tool.',
        'floor_plan_result': 'Result: The function generated 4 paid conversions within 3 days of launch.',
        'cosplay_generator_desc': 'AI cosplay generator, focusing on the generation of anime and game characters.',
        'professional_photo_desc': 'AI professional photo generator, providing users with professional business portraits.',
        # Web Picture Scraper page content
        'webscraper_page_subtitle': 'Batch Image Download Tool - Self-developed workflow optimization tool during internship, achieving automation of image batch downloading.',
        'webscraper_overview_p1': 'Web Picture Scraper is a self-use tool I independently developed to optimize team workflow during my internship.',
        'webscraper_overview_p2': 'In daily work, I often need to find and download specific theme image materials. The traditional method of saving images one by one by right-clicking is extremely inefficient. Therefore, I developed this web image scraper tool. Just by entering a link, you can batch download images. This not only solved my own efficiency problems, but was also shared with colleagues. It saves team members an average of about 30 minutes of repetitive work time per day.',
        'webscraper_bg_title': 'Solving Work Pain Points',
        'webscraper_bg_p': 'In daily work, I often need to collect image materials from various websites for design and analysis. The traditional manual right-click save method is extremely inefficient, especially when facing web pages containing a large number of images.',
        'webscraper_bg_li1': 'Manual image saving is time-consuming and inefficient',
        'webscraper_bg_li2': 'Easy to miss hidden images on web pages',
        'webscraper_bg_li3': 'Unable to batch process multiple web pages',
        'webscraper_bg_li4': 'Lack of image classification and management functions',
        'webscraper_role_title': 'Independent Full-Stack Developer',
        'webscraper_role_li1': 'Requirements analysis and product design',
        'webscraper_role_li2': 'Frontend interface development and user experience design',
        'webscraper_role_li3': 'Backend API development and crawler logic implementation',
        'webscraper_role_li4': 'Database design and data management',
        'webscraper_role_li5': 'Cloud deployment and operations monitoring',
        'webscraper_tech_frontend': 'Frontend Interface & User Experience',
        'webscraper_tech_frontend_p': 'Designed a simple and intuitive user interface to ensure users can get started quickly.',
        'webscraper_tech_frontend_li1': 'Responsive design, supporting desktop and mobile access',
        'webscraper_tech_frontend_li2': 'Real-time progress display, users can see crawling progress',
        'webscraper_tech_frontend_li3': 'Image preview function, supporting batch selection and download',
        'webscraper_tech_frontend_li4': 'Error handling mechanism, friendly error messages',
        'webscraper_tech_backend': 'Backend Crawler Technology',
        'webscraper_tech_backend_p': 'Developed an efficient and stable web crawler system capable of intelligently identifying and crawling various types of images.',
        'webscraper_tech_backend_li1': 'Supports multiple image formats: JPG, PNG, GIF, WebP, etc.',
        'webscraper_tech_backend_li2': 'Smart deduplication algorithm to avoid downloading duplicate images',
        'webscraper_tech_backend_li3': 'Anti-crawler mechanism handling to ensure crawling stability',
        'webscraper_tech_backend_li4': 'Asynchronous processing architecture to improve crawling efficiency',
        'webscraper_tech_deploy': 'Performance Optimization & Deployment',
        'webscraper_tech_deploy_p': 'Comprehensive optimization for performance and user experience to ensure the practicality and stability of the tool.',
        'webscraper_tech_deploy_li1': 'Image compression and format conversion to reduce download size',
        'webscraper_tech_deploy_li2': 'CDN acceleration to improve global access speed',
        'webscraper_tech_deploy_li3': 'Fault tolerance mechanism to handle network exceptions and timeouts',
        'webscraper_tech_deploy_li4': 'Monitoring and alerting for real-time system operation status',
        'webscraper_challenge_title': 'Challenge: Anti-crawler Mechanism',
        'webscraper_challenge_p': 'Many websites have anti-crawler protection and need to simulate real user behavior',
        'webscraper_solution': 'Solution:',
        'webscraper_solution_1': 'Implemented User-Agent rotation, request delays and proxy pool mechanism',
        'webscraper_challenge2_title': 'Challenge: Image Format Compatibility',
        'webscraper_challenge2_p': 'Different websites use various image formats and encoding methods',
        'webscraper_solution_2': 'Developed a universal image detection and conversion algorithm',
        'webscraper_challenge3_title': 'Challenge: Cloud Deployment Cost',
        'webscraper_challenge3_p': 'Need to achieve stable cloud services within a limited budget',
        'webscraper_solution_3': 'Selected cost-effective Render platform and optimized resource usage',
        'webscraper_lesson1': 'Problem-oriented product thinking: Developing tools that truly solve problems starting from actual work pain points is more valuable than pursuing technical coolness.',
        'webscraper_lesson2': 'Full-stack development gains: Completing the entire project independently gave me a deep understanding of the full product development process and improved my comprehensive problem-solving ability.',
        'webscraper_lesson3': 'Importance of user experience: No matter how perfect the technical implementation is, if the user experience is poor, the product loses its value.',
        'webscraper_cta_title': 'Interested in my full-stack development capabilities?',
        'webscraper_cta_p': 'Let\'s explore how to build products from 0 to 1 that solve real problems.',
        'one_person': '1 person (Independent Development)',
        'internship_self_tool': 'Internship Self-developed Tool',
        'chat_limit_reached': 'Limit reached. Please reset to start a new conversation.',
        'chat_error_prefix': 'Error: ',
        'chat_network_error': 'Network error. Please try again.',
        # Typing animation phrases
        'typing_phrase_2': 'AI Product Manager',
        'typing_phrase_3': 'Builder & Creator',
        # Chatbot initial messages
        'chat_init_personal': 'Hi! I\'m Zhou Jing. Nice to meet you! Feel free to ask me about my project experience, skills, or anything else.',
        'chat_init_general': 'Hello! I\'m a general AI assistant. Feel free to ask me anything.',
        # New project experiences from resume
        'project_momenta_title': 'Momenta',
        'project_momenta_subtitle': 'Multimodal AI Emotion-based Music Generation App',
        'project_momenta_date': '2026.01 - Present',
        'project_momenta_role': 'Product Manager & AI Engineer',
        'project_momenta_location': 'Hong Kong',
        'project_momenta_badge': 'Coming to App Store',
        'project_momenta_1': 'Product planning & prototyping: Based on user interviews and competitive analysis, defined product roadmap and MVP scope. Completed full iOS UI/UX design in Figma/Pencil.',
        'project_momenta_2': 'Tech architecture & engineering: Independently handled full-stack iOS development with Xcode + SwiftUI. Overcame the challenge of replicating iOS 26\'s Liquid Glass effect by deep-diving into Apple\'s official developer documentation, locating the correct APIs, and achieving a native-feel fluid UI.',
        'project_momenta_3': 'Self-taught and integrated Supabase cloud backend from scratch for user config management, cloud data sync, and auth system. Implemented Google Sign-In and Apple ID Sign-In OAuth protocols, demonstrating strong problem-solving ability and execution.',
        'project_momenta_4': 'AI model integration: Designed multimodal prompt logic, called OpenAI API for semantic & visual analysis, integrated Suno AI with HealthKit & WeatherKit for end-to-end automated music generation from physiological/environmental data.',
        'project_momenta_5': 'Expected to launch on App Store in March 2026. Currently in final development and testing phase.',
        'project_nanobanana_role': 'Co-founder & Product Operations',
        'project_nanobanana_date': '2025.09 - Present',
        'project_nanobanana_1': 'Product & feature iteration: Led design and delivery of 6+ core AI features. Independently completed full workflow from requirements analysis to page logic design and frontend copywriting.',
        'project_nanobanana_2': 'Prompt engineering optimization: Deeply optimized prompt logic, significantly improving image controllability and aesthetic quality, resolving multiple generation failures and boosting user satisfaction.',
        'project_nanobanana_3': 'Growth & SEO: Formulated programmatic SEO strategy — core pages rank #1 on Bing and Top 3 on Google, driving sustained free organic traffic. Total page views approaching 800K.',
        'project_nanobanana_4': 'Full-stack collaboration: As a "PM who can code", used Python automation scripts for competitive research and keyword mining, translating data insights into actionable feature requirements.',
        'project_nanobanana_5': 'Business results: The platform has achieved profitability with ~10K RMB monthly revenue, validating the product-market fit of the AI image generation vertical.',
        'project_loreal_title': 'L\'Oréal Brandstorm',
        'project_loreal_subtitle': 'NFT-driven Beauty Metaverse Strategy',
        'project_loreal_date': '2022.01 - 2022.04',
        'project_loreal_role': 'Product Planning & UI Designer',
        'project_loreal_1': 'Led the conceptualization of a Web3 strategy using NFT technology to build a L\'Oréal metaverse community. The proposal gained significant social media traction and advanced the team to the official Mock-up Session.',
        'project_loreal_2': 'Designed the complete user journey: "Purchase limited gift box → Bind exclusive NFT → Spend points to upgrade NFT avatar → Cross-platform game collaboration", plus innovative offline-online NFT redemption mechanics.',
        'project_loreal_3': 'As team designer, independently produced the full English business plan (PPT) and designed UI prototypes for the NFT membership system and avatar upgrade flows.',
        'project_mooncake_title': '"Yi Qi Yi Li" Campus Mooncake Project',
        'project_mooncake_date': '2022.06 - 2022.10',
        'project_mooncake_role': 'Project Lead',
        'project_mooncake_1': 'Led a 30-person team from 0 to 1, overseeing product design, supply chain, marketing, and sales. Sold 1,500 gift boxes + 500 gift bags, achieving 50K+ RMB net profit.',
        'project_mooncake_2': 'Built an integrated marketing matrix of "Mini-program + 350-member community + offline pop-up", driving campus sales through cross-platform livestreams, group buying, and social referrals — resulting in complete sellout.',
        'project_mooncake_3': 'Secured support from 2 official university departments and was featured by the Communist Youth League\'s official account "Jin Cai Qing Chun", significantly enhancing brand influence.',
        # Campus experience
        'campus_arts_title': 'Arts Department Officer',
        'campus_arts_org': 'Student Union, College of Humanities',
        'campus_arts_date': '2020.09 - 2021.09',
        'campus_arts_1': 'Organized and managed 4 major campus events including Freshman Gala and Culture Festival, reaching 2000+ participants.',
        'campus_arts_2': 'Coordinated 10+ technical aspects (lighting, sound, props) with detailed scheduling to ensure zero-error show execution.',
        # Skills section
        'skill_product_design': 'Product Design & Planning',
        'skill_product_design_desc': 'Proficient in Figma & Sketch for high-fidelity prototyping; expert in Xmind for business flow diagrams; strong PRD documentation skills.',
        'skill_ai_tech': 'AI Technology & Application',
        'skill_ai_tech_desc': 'Expert in Prompt Engineering (Midjourney/SD/ChatGPT/Suno); Python (web scraping/data cleaning/NLP basics); iOS Development (SwiftUI/Xcode); Supabase; SQL basics.',
        'skill_data_growth': 'Data Analysis & Growth',
        'skill_data_growth_desc': 'Skilled in Programmatic SEO strategy; Google Analytics (GA4) traffic analysis; A/B Testing; Excel (pivot tables), Tableau, SPSS for data analysis.',
        'skill_tools': 'General Tools',
        'skill_tools_desc': 'Notion & Feishu for project management; Git/GitHub version control; PS, Pr, Ae for multimedia production.',
        # Other info
        'other_language': 'Languages',
        'other_language_desc': 'English (IELTS 6.5), Cantonese',
        'other_hobbies': 'Hobbies',
        'other_hobbies_desc': 'Badminton, Photography, Film Photography, Hiking',
    },
    'zh': {
        'nav_home': '首页',
        'nav_resume': '简历',
        'nav_projects': '项目',
        'hero_title': 'Zhou Jing 周晶',
        'hero_subtitle': 'AI产品经理 | 香港理工大学计算机硕士（生成式AI） | 全栈产品构建者',
        'hero_tags_row1': ['香港理工大学计算机硕士 (QS 54)', '新加坡国立大学交换 (QS前50)', 'AI产品实习生', 'AIGC SaaS联合创始人', 'iOS开发', 'Prompt Engineering', 'Programmatic SEO', 'Python', 'SwiftUI', 'Figma'],
        'hero_tags_row2': ['国家奖学金（前1%）', '天津市优秀学生', 'GPA 3.8/4', '欧莱雅Brandstorm', 'iOS App（即将上线App Store）', '羽毛球 🏸', '摄影 📹'],
        'hero_description': '兼具生成式AI计算机专业背景与产品开发实战经验，我能从概念到上线全链路构建AI产品——可以写代码、做设计、做增长。',
        'btn_view_projects': '查看我的项目',
        'btn_view_resume': '查看我的简历',
        'highlights_title': '亮点',
        'highlights_subtitle': '用数字讲述我的故事。',
        'highlight_education': 'QS 54 名校',
        'highlight_education_desc': '理工大学计算机硕士（生成式AI）+ 新加坡国立大学交换（QS前50）',
        'highlight_ai_skills': '全栈AI产品构建者',
        'highlight_ai_skills_desc': 'iOS App + AIGC SaaS + Python自动化——从产品到代码',
        'highlight_scholarship': '国家奖学金',
        'highlight_scholarship_desc': 'GPA 3.8/4，全国前1%',
        'highlight_competitions': '20+ 荣誉奖项',
        'highlight_competitions_desc': '国家奖学金、微电影大赛全国二等奖、大广赛全国一等奖、天津市优秀学生等',
        'btn_view_resume': '查看我的简历',
        'ai_section_title': '随便问',
        'ai_section_subtitle': '和我的 AI 分身聊天。',
        'ai_chat_title': 'AI助手',
        'ai_status_online': '在线并准备帮助',
        'ai_welcome_message': '您好！我是周晶的AI助手。请随时询问她的项目、技能、经验或任何您想了解的内容！',
        'ai_chat_placeholder': '询问我的项目或技能...',
        'chat_mode_label': '模式:',
        'chat_mode_personal': '个人模式（关于我）',
        'chat_mode_general': '通用模式（自由对话）',
        'chat_model_label': 'AI模型:',
        'featured_projects_title': '项目',
        'featured_projects_subtitle': '从概念到上线。',
        'skills_title': '我的工具箱',
        'footer_contact': '联系方式',
        'footer_copyright': '© 2026 Zhou Jing 周晶',
        # Projects page - categories
        'projects_page_title': '项目',
        'projects_page_subtitle': '我构建或参与的产品和工具。',
        'category_all': '全部',
        'category_ai_products': 'AI 产品',
        'category_simple_tools': '轻量工具',
        'project_type_saas': 'SaaS',
        'project_type_tool': '工具',
        # Dropdown menu items
        'dropdown_all_projects': '所有项目',
        'dropdown_musiccreator_ai': 'MusicCreator AI',
        'dropdown_coloringbook_ai': 'Coloringbook AI',
        'dropdown_inker_ai': 'Inker.AI', 
        'dropdown_web_picture_scraper': 'Web Picture Scraper',
        'dropdown_nanobanana_ai': 'NanoBanana AI',
        'dropdown_all_creative': '所有创意作品',
        'dropdown_film_video': '影视作品',
        'dropdown_digital': '数字互动',
        'dropdown_photography': '摄影作品',
        'dropdown_graphic': '平面设计',
        # Resume page
        'resume_title': '简历',
        'resume_current_role': '香港理工大学计算机科学与技术硕士（生成式AI） | AI产品经理',
        'resume_about_title': '关于我',
        'resume_about_text': 'AI产品经理，香港理工大学（QS 54）计算机硕士在读。兼具产品思维与工程执行力——擅长iOS全栈开发、Prompt工程、程序化SEO和数据驱动增长。热衷于从0到1构建AI产品。',
        'resume_experience_title': '工作经历',
        'resume_education_title': '教育经历',
        'resume_honors_title': '荣誉奖项',
        'resume_projects_title': '项目经历',
        'resume_skills_title': '专业技能',
        'resume_campus_title': '校园经历',
        # Index page - view more projects button
        'view_more_projects': '查看所有项目',
        # Project descriptions on index page
        'project_musiccreator_desc': 'AI音乐生成器平台，通过产品调研、新增功能开发、prompt工程和SEO优化，打造直观的音乐创作体验。',
        'project_coloringbook_desc': 'AI填色页生成器，专注于用户体验设计，通过新增功能、prompt工程、SEO和bug修复，为所有年龄段用户提供创意表达平台。',
        'project_inker_desc': 'AI纹身设计生成器，负责新增功能开发、prompt工程优化和SEO策略，帮助用户创造个性化纹身设计。',
        'project_webscraper_desc': '网页图片抓取工具，独立完成前端、后端、部署全栈开发，解决工作中图片收集效率低的痛点问题。',
        'project_nanobanana_desc': 'AI图像生成器，在3人创业团队中主要负责功能调研、开发实现、prompt工程和SEO优化。',
        # AI Projects page
        'ai_projects_page_title': 'AI产品项目经验',
        'ai_projects_page_subtitle': '从功能调研到SEO优化，深度参与AI产品全链路运营',
        'status_operating': '运营中',
        'status_internship': '实习项目',
        'status_self_developed': '自研工具',
        'total_traffic': '总流量',
        'daily_traffic': '日均流量',
        'monthly_visits': '月访问量',
        'conversion_3days': '3天转化',
        'bing_ranking': 'Bing排名',
        'google_ranking': 'Google排名',
        'time_saved_daily': '日节省工时',
        'internal_users': '内部用户',
        'view_details': '查看详情',
        'core_capabilities': '核心能力',
        'feature_research': '功能调研',
        'market_research': '市场需求分析',
        'prompt_engineering': 'Prompt工程',
        'ai_output_optimization': 'AI输出优化',
        'seo_geo_optimization': 'SEO/GEO优化',
        'traffic_growth_strategy': '流量增长策略',
        'fullstack_development': '全栈开发',
        'tool_self_development': '工具自主开发',
        'project_details': '项目详情',
        'team_role': '团队角色',
        'main_responsibilities': '主要职责',
        'operating_status': '运营状态',
        'other_projects': '其他项目',
        # Creative Works page
        'creative_works_subtitle': '我的媒体与设计专业能力展示',
        'portfolio_under_construction': '作品集建设中',
        'portfolio_description': '这个创意作品集展示了我在影视、摄影、平面设计和数字互动媒体方面的作品，即将上线。',
        'preview_categories': '预览分类',
        'film_video_title': '影视作品',
        'film_video_desc': '短片、纪录片和视频制作',
        'photography_title': '摄影作品',
        'photography_desc': '人像、风景和艺术摄影',
        'graphic_design_title': '平面设计',
        'graphic_design_desc': '海报、品牌和视觉识别作品',
        'digital_interactive_title': '数字互动',
        'digital_interactive_desc': 'AIGC图像、SVG设计和H5页面',
        'back_to_home': '返回首页',
        'learn_about_me': '了解更多关于我',
        # Resume page - detailed content
        'internship_pipi_title': 'AI产品实习生，AI产品2组',
        'internship_pipi_company': '广州皮皮电商科技有限公司',
        'internship_pipi_location': '广州',
        'core_competencies_title': '核心能力',
        'product_management': '产品管理',
        'ai_technology': 'AI与技术',
        'design_media': '设计与媒体',
        # Badge and Tag translations
        'badge_product_research': '产品调研',
        'badge_feature_development': '功能开发',
        'badge_new_features': '新增功能',
        'badge_frontend_dev': '前端开发',
        'badge_backend_dev': '后端开发',
        'badge_fullstack_deploy': '全栈部署',
        'badge_efficiency_tool': '效率工具',
        'badge_bug_fix': 'Bug修复',
        'badge_seo': 'SEO优化',
        'badge_feature_planning': '功能调研',
        'badge_topic_page': '专题页撰写',
        # AI Projects page - detailed project info
        'nanobanana_subtitle': 'AI图像生成与编辑平台',
        'nanobanana_description': '与创业团队合作，负责功能调研、专题页策划、SEO/GEO优化等全链路产品运营工作。',
        'musiccreator_subtitle': 'AI音乐生成平台',
        'musiccreator_description': '负责产品调研、Prompt工程及SEO优化，推动产品功能迭代与流量增长。',
        'coloringbook_subtitle': 'AI填色页生成平台',
        'coloringbook_description': '负责功能调研、Prompt工程及SEO优化，核心功能页Google搜索排名第一。',
        'inker_subtitle': 'AI纹身设计生成平台',
        'inker_description': '负责功能调研、Prompt工程及SEO优化，探索细分市场的AI应用场景。',
        'webscraper_subtitle': '图片批量下载工具',
        'webscraper_description': '实习期间自主开发的工作流优化工具，实现图片批量下载自动化。',
        'stopped_operations': '停止运营',
        'bing_midi_editor': 'Bing MIDI Editor',
        # Resume page - Experience section titles and companies
        'intern_marketing': '市场部实习生，市场部',
        'intern_product': '产品实习生，AI产品组2',
        'intern_newmedia': '新媒体营销实习生，市场部',
        'intern_journalist': '记者实习生',
        'company_jiangmen': '将门投资管理顾问（北京）有限公司',
        'company_netease': '网易游戏',
        'company_zhongshan': '中山日报',
        'location_beijing': '北京',
        'location_guangzhou': '广州',
        'location_zhongshan': '中山',
        # Education section
        'edu_msc_title': '计算机科学与技术（生成式人工智能与人文科学）硕士',
        'edu_polyu': '香港理工大学',
        'edu_polyu_desc': '海外QS前100 | USNEWS 100',
        'edu_msc_desc': '课程：计算机视觉，机器学习，计算机编程，人机交互，自然语言处理。',
        'edu_msc_date': '2025.09 - 2026.07',
        'edu_exchange_title': '金融科技和数字商业（交流项目）',
        'edu_nus': '新加坡国立大学',
        'edu_nus_desc': 'USNEWS前50 | 海外QS前50',
        'edu_exchange_desc': '荣誉：新加坡国立大学交换成果奖学金，结课证书。',
        'edu_nus_date': '2023.01 - 2023.02',
        'edu_bachelor_title': '广播电视学（财经新闻）本科',
        'edu_tjufe': '天津财经大学',
        'edu_bachelor_desc': '绩点：3.8/4（前1%）。荣誉：国家奖学金，天津市优秀学生，连续三年一等奖学金，优秀学生。',
        'edu_tjufe_date': '2020.09 - 2024.06',
        # Honors section - National level
        'honor_national_scholarship': '国家奖学金（全国前1%学生获得）',
        'honor_national_scholarship_date': '2022-2023',
        'honor_microfilm_national': '高校大学生思政微电影二等奖（国家级）',
        'honor_microfilm_national_date': '2023.05',
        'honor_meihao_national': '善创未来，美好大会创新大赛一等奖（国家级）',
        'honor_meihao_national_date': '2021',
        'honor_ad_national': '全国大学生广告艺术大赛一等奖（省级）',
        'honor_ad_national_date': '2022.07',
        # Provincial level
        'honor_tianjin_student': '天津市优秀学生（省级）',
        'honor_tianjin_student_date': '2022-2023',
        'honor_microfilm_provincial_1st': '高校思政微电影一等奖（省级）',
        'honor_microfilm_provincial_1st_date': '2022.08',
        'honor_microfilm_provincial_3rd': '高校思政微电影三等奖（省级）',
        'honor_microfilm_provincial_3rd_date': '2021.09',
        # University level
        'honor_graduate': '优秀毕业生（校级）',
        'honor_graduate_date': '2024',
        'honor_nus_exchange': '新加坡国立大学交换项目成果奖学金',
        'honor_nus_exchange_date': '2023',
        'honor_first_scholarship': '一等奖学金（校级）',
        'honor_first_scholarship_date': '2020-2023',
        'honor_outstanding_student': '优秀学生（校级）',
        'honor_outstanding_student_date': '2020-2023',
        'honor_outstanding_league': '优秀团员（校级）',
        'honor_outstanding_league_date': '2020-2022',
        'honor_innovation_training': '大学生创新创业训练计划结项（校级）',
        'honor_innovation_training_date': '2023.09',
        'honor_srt': '本科生科研训练计划SRT结项（校级）',
        'honor_srt_date': '2022.10',
        'honor_internet_plus_3rd_2022': '"互联网+"大学生创业大赛三等奖（校级）',
        'honor_internet_plus_3rd_2022_date': '2022.06',
        'honor_creative_challenge_1st': '"创新创意创业挑战赛"一等奖（校级）',
        'honor_creative_challenge_1st_date': '2022.05',
        'honor_internet_plus_3rd_2021': '"互联网+"大学生创业大赛三等奖（校级）',
        'honor_internet_plus_3rd_2021_date': '2021.06',
        # Honor level labels
        'honor_level_national': '国家级',
        'honor_level_provincial': '省级',
        'honor_level_university': '校级',
        # Projects section
        'projects_intro': '详细案例研究和项目作品集，请访问：',
        'projects_ai_portfolio': 'AI项目作品集',
        'projects_creative_portfolio': '创意作品作品集',
        'projects_selected': '精选项目',
        'project_ai_music': 'AI音乐生成器平台：从用户研究到上线的端到端产品开发',
        'project_ai_coloring': 'AI填色书应用：以用户为中心的设计和AI集成创意工具',
        'project_python_tools': 'Python网页抓取工具：产品洞察的数据收集和分析自动化',
        'project_interactive': '互动媒体项目：获奖的数字故事讲述和用户体验设计',
        # Core Competencies section
        'competency_user_research': '用户研究与分析',
        'competency_product_strategy': '产品策略与路线图',
        'competency_ab_testing': 'A/B测试与指标',
        'competency_agile': '敏捷/Scrum方法论',
        'competency_leadership': '跨职能领导力',
        'competency_ml': '机器学习概念',
        'competency_python': 'Python编程',
        'competency_api': 'API集成',
        'competency_data_analysis': '数据分析与可视化',
        'competency_video': '视频制作',
        'competency_photography': '数字摄影',
        'competency_content': '内容策略',
        'competency_seo': 'SEO优化',
        # AI Project detail pages - common labels
        'visit_product': '访问产品',
        'back_to_projects': '返回项目列表',
        'project_overview': '项目概述',
        'responsible_content': '负责内容与功能页展示',
        'core_achievements': '核心成果',
        'internship_role': '实习生',
        'startup_member': '创业团队成员',
        'independent_developer': '独立开发者',
        'project_nature': '项目性质',
        'team_size': '团队规模',
        'my_role': '我的角色',
        'tech_stack': '技术栈',
        'application_scope': '应用范围',
        'core_tech': '核心技术',
        'team_internal_use': '团队内部使用',
        'interested_in_fullstack': '对我的全栈开发能力感兴趣？',
        'explore_build_products': '让我们探讨如何从0到1构建解决实际问题的产品。',
        'view_resume': '查看我的简历',
        'view_more_projects_btn': '查看更多项目',
        'project_background': '项目背景与动机',
        'solve_pain_points': '解决工作痛点',
        'fullstack_responsibilities': '我的全栈开发职责',
        'tech_highlights': '技术实现亮点',
        'frontend_ui': '前端界面与用户体验',
        'backend_crawler': '后端爬虫技术',
        'performance_deploy': '性能优化与部署',
        'project_results': '项目成果',
        'automation_download': '自动化下载',
        'no_repetitive_work': '重复劳动',
        'tech_challenges': '技术挑战与解决方案',
        'experience_summary': '经验总结',
        'minutes': '分钟',
        '30_minutes': '30分钟',
        '4_orders': '4单',
        # Resume Experience Section - Detailed descriptions
        'exp_pipi_1': '竞品调研与需求挖掘：主导10款AI竞品的深度调研，通过Python自动化脚本抓取并分析8万条关键词数据，提炼出30+项核心需求，为产品迭代提供了关键的市场洞察。',
        'exp_pipi_2': '功能策划与文档撰写：设计并上线11+项创新AI功能（AI音乐、填色页等）。负责撰写包含界面布局、交互逻辑与文案细节的产品需求文档（PRD），并配合Figma原型演示，有效降低了设计与开发的沟通成本。',
        'exp_pipi_3': '优化了产品底层提示词工程，通过精准的提示词设计，有效修复了多项产品Bug，提升了AI功能的稳定性和用户满意度。',
        'exp_pipi_4': 'SEO专题页策划：执行程序化SEO策略，策划并落地88个专题页面的结构设计与内容布局。成功搭建35条外链，其中14条生效，显著提升了搜索引擎排名和自然流量。同时负责多语言内容本地化，拓展国际市场。',
        'exp_pipi_5': '策划并执行了EDM营销活动，通过A/B测试优化邮件内容和发送策略，并根据用户付费状态进行精准广告推送。',
        'exp_pipi_6': '引入并应用AI工具优化了多项日常工作流程，成功将重复性工作时间节省了1小时以上，显著提升了团队整体工作效率。',
        'exp_jiangmen_subtitle1': '1. 新媒体运营',
        'exp_jiangmen_subtitle2': '2. 社区运营',
        'exp_jiangmen_platforms': '（公众号、知乎、B站、微博、CSDN、YouTube）',
        'exp_jiangmen_1': '负责2个公众号的编辑、审核和运营，发布150+篇技术文章、50+篇品牌公关文和10+篇活动文。根据账号数据开设新栏目，增强用户粘性，实现账号净增长从负到正。',
        'exp_jiangmen_2': '负责新媒体平台（知乎、B站、微博、CSDN、YouTube）的内容更新、审核和维护。相比接手前，坚持每周至少三次的定期更新频率和平台高活跃度。',
        'exp_jiangmen_3': '负责内容策划和原创内容输出，如节日热点策划、短视频策划制作等，互动量和阅读量高。',
        'exp_jiangmen_4': '进行新媒体矩阵月度数据分析并完成可视化报告。通过分析和针对性的账号优化建议，平均完成率提高15%。',
        'exp_jiangmen_community': '（TechBeat人工智能社区）',
        'exp_jiangmen_5': '协助运营TechBeat人工智能社区，编辑排版技术文章380+篇，熟悉markdown和Latex公式编辑器。全流程完成Talk并上架共80+期。',
        'exp_jiangmen_6': '通过知乎、公众号、Twitter、csdn和Arxiv，探索前沿技术文章解读并邀约作者入驻社区，成功邀请20+人工智能领域大牛入驻社区。',
        'exp_jiangmen_7': '协助完成社区月度数据报告，熟练使用Growing io监控网站进行产品分析和获客分析。',
        'exp_netease_1': '负责《决战！平安京》游戏的微博账号@决战平安京优酒酱，独立策划并完成图文制作发布1156篇，制作并发布38个视频（15s-1min），净增粉丝2w。',
        'exp_netease_2': '跟进OPL决战平安京职业联赛春夏赛季的前期营销工作和赛季宣传。具体任务为实时直播比赛、赛后整理高光时刻、制作图文视频。共跟进28场直播112小时，其中单场直播约4小时，特殊直播会延长至6小时。',
        'exp_netease_3': '参与OPL营销活动策划，制造热门话题提高讨论度：OPL赛季两支顶级战队相遇时的"宿敌会"热门话题事件；决赛前期策划的花式话题事件。',
        'exp_zhongshan_1': '作为记者实习生，负责新闻采集、撰写和编辑，涉及政治新闻、法律新闻、三农新闻、娱乐新闻等板块。',
        'exp_zhongshan_2': '完成80+次采访和40+篇新闻报道。所有文章均成功在中山日报和中山"加"APP上发表。',
        'exp_zhongshan_3': '其中4篇文章同时上了学习强国，累计阅读15W。最高文章《三农新闻发挥余热，中山老技术员帮助新品种作物顺利》达到阅读量91512和点赞量5883。',
        # AI Project detail page descriptions
        'musiccreator_overview': 'MusicCreator AI 是我在实习期间参与的一个AI音乐创作平台项目。我主要负责针对不同音乐风格和功能模块的竞品调研、Prompt工程优化，以及多个核心功能页面的SEO内容建设。',
        'coloringbook_overview': 'Coloringbook AI 是我在实习期间参与的一个AI填色页生成平台。我主要负责核心功能的市场调研、Prompt工程优化，以及相关功能页面的SEO内容建设，旨在提升产品的自然搜索流量。',
        'inker_overview': 'Inker.AI 是我在实习期间参与的一个AI纹身设计平台。我主要负责产品的市场调研、功能策划、Prompt工程优化以及核心功能页面的SEO内容建设，帮助用户通过AI实现独特的纹身创意。',
        'nanobanana_overview': 'NanoBanana AI 是一个我目前正在运营的创业项目。我作为核心成员，主要负责产品新功能的市场调研、功能专题页的策划与撰写，以及针对全球不同地区的SEO和GEO优化策略，旨在提升产品的搜索排名和用户转化。',
        'webscraper_overview': 'Web Picture Scraper是我在实习期间为优化团队工作流程而独立开发的一款自用小工具。',
        'responsible_pages': '我负责了以下功能页面的内容策划与优化：',
        'responsible_pages_nanobanana': '我主导了以下核心功能页面的内容建设与优化：',
        'achievement_result': '成果：',
        'achievement_monthly_traffic': '月流量',
        'achievement_daily_traffic': '日流量',
        'achievement_precise_traffic': '的精准月流量',
        # MusicCreator AI feature descriptions
        'midi_editor_desc': '在线MIDI编辑器。',
        'midi_editor_result': '成果：该页面Bing搜索排名第一，"midi"关键词带来1k月流量。',
        'audio_to_midi_desc': '音频转MIDI工具。',
        'audio_to_midi_result': '成果：我撰写的"audio to midi"关键词带来940的精准月流量。',
        'ai_mastering_desc': 'AI母带处理',
        'text_to_music_desc': '文本转音乐',
        'ai_singing_desc': 'AI歌声生成',
        'ai_rap_desc': 'AI说唱生成',
        'photo_to_music_desc': '图片转音乐',
        'lofi_converter_desc': 'Lofi音乐转换器',
        'birthday_song_desc': '生日歌生成器',
        'dubstep_maker_desc': 'Dubstep制作器',
        # Coloringbook AI feature descriptions
        'coloring_book_desc': 'AI填色书生成器。',
        'coloring_book_result': '成果：该功能在Google搜索排名第一，是整个产品收益贡献最大的核心功能。',
        'name_coloring_desc': '名字填色页生成器，满足用户的个性化定制需求。',
        # Inker.AI feature descriptions
        'birth_flower_tattoo_desc': '生日花纹身生成器。针对纹身细分市场，提供结合生日花语的个性化纹身设计服务。',
        # NanoBanana AI feature descriptions  
        'ai_image_combiner_desc': '智能图片融合工具。',
        'ai_image_combiner_result': '成果：该页面在Bing搜索结果中排名第一。',
        'floor_plan_desc': 'AI户型图生成工具。',
        'floor_plan_result': '成果：功能上线仅3天即产生4单付费转化。',
        'cosplay_generator_desc': 'AI角色扮演生成器，专注于二次元与游戏角色的生成。',
        'professional_photo_desc': 'AI职业形象照生成器，为用户提供专业的商务人像。',
        # Web Picture Scraper page content
        'webscraper_page_subtitle': '图片批量下载工具 - 实习期间自主开发的工作流优化工具，实现图片批量下载自动化。',
        'webscraper_overview_p1': 'Web Picture Scraper是我在实习期间为优化团队工作流程而独立开发的一款自用小工具。',
        'webscraper_overview_p2': '针对日常工作中需要频繁寻找和下载特定主题图片素材的痛点，传统的一次次右键保存方式效率极低。因此，我开发了这个网页图片爬虫工具，只需输入链接即可批量下载图片，不仅解决了自己的效率问题，也分享给同事使用，平均每天能为团队成员节省约30分钟的重复性工作时间。',
        'webscraper_bg_title': '解决工作痛点',
        'webscraper_bg_p': '在日常工作中，经常需要从各种网站收集图片素材用于设计和分析，传统的手动右键保存方式效率极低，特别是面对包含大量图片的网页时。',
        'webscraper_bg_li1': '手动保存图片耗时费力，效率低下',
        'webscraper_bg_li2': '容易遗漏网页中的隐藏图片',
        'webscraper_bg_li3': '无法批量处理多个网页',
        'webscraper_bg_li4': '缺乏图片分类和管理功能',
        'webscraper_role_title': '独立全栈开发者',
        'webscraper_role_li1': '需求分析和产品设计',
        'webscraper_role_li2': '前端界面开发和用户体验设计',
        'webscraper_role_li3': '后端API开发和爬虫逻辑实现',
        'webscraper_role_li4': '数据库设计和数据管理',
        'webscraper_role_li5': '云端部署和运维监控',
        'webscraper_tech_frontend': '前端界面与用户体验',
        'webscraper_tech_frontend_p': '设计了简洁直观的用户界面，确保用户能够快速上手使用。',
        'webscraper_tech_frontend_li1': '响应式设计，支持桌面和移动端访问',
        'webscraper_tech_frontend_li2': '实时进度显示，用户可以看到抓取进度',
        'webscraper_tech_frontend_li3': '图片预览功能，支持批量选择和下载',
        'webscraper_tech_frontend_li4': '错误处理机制，友好的错误提示信息',
        'webscraper_tech_backend': '后端爬虫技术',
        'webscraper_tech_backend_p': '开发了高效稳定的网页爬虫系统，能够智能识别和抓取各类图片。',
        'webscraper_tech_backend_li1': '支持多种图片格式：JPG、PNG、GIF、WebP等',
        'webscraper_tech_backend_li2': '智能去重算法，避免下载重复图片',
        'webscraper_tech_backend_li3': '反爬虫机制处理，确保抓取稳定性',
        'webscraper_tech_backend_li4': '异步处理架构，提升抓取效率',
        'webscraper_tech_deploy': '性能优化与部署',
        'webscraper_tech_deploy_p': '针对性能和用户体验进行了全面优化，确保工具的实用性和稳定性。',
        'webscraper_tech_deploy_li1': '图片压缩和格式转换，减少下载体积',
        'webscraper_tech_deploy_li2': 'CDN加速，提升全球访问速度',
        'webscraper_tech_deploy_li3': '容错机制，处理网络异常和超时',
        'webscraper_tech_deploy_li4': '监控告警，实时掌握系统运行状态',
        'webscraper_challenge_title': '挑战：反爬虫机制',
        'webscraper_challenge_p': '许多网站有反爬虫保护，需要模拟真实用户行为',
        'webscraper_solution': '解决方案：',
        'webscraper_solution_1': '实现了User-Agent轮换、请求延迟和代理池机制',
        'webscraper_challenge2_title': '挑战：图片格式兼容性',
        'webscraper_challenge2_p': '不同网站使用各种图片格式和编码方式',
        'webscraper_solution_2': '开发了通用的图片检测和转换算法',
        'webscraper_challenge3_title': '挑战：云端部署成本',
        'webscraper_challenge3_p': '需要在有限预算内实现稳定的云端服务',
        'webscraper_solution_3': '选择了性价比高的Render平台，优化了资源使用',
        'webscraper_lesson1': '问题导向的产品思维：从实际工作痛点出发，开发真正解决问题的工具比追求技术炫酷更有价值。',
        'webscraper_lesson2': '全栈开发的收获：独立完成整个项目让我深刻理解了产品开发的全流程，提升了解决问题的综合能力。',
        'webscraper_lesson3': '用户体验的重要性：技术实现再完美，如果用户体验不佳，产品就失去了价值。',
        'webscraper_cta_title': '对我的全栈开发能力感兴趣？',
        'webscraper_cta_p': '让我们探讨如何从0到1构建解决实际问题的产品。',
        'one_person': '1人（独立开发）',
        'internship_self_tool': '实习期间自研工具',
        'chat_limit_reached': '已达对话上限，请重置以开始新对话。',
        'chat_error_prefix': '错误：',
        'chat_network_error': '网络错误，请重试。',
        # Typing animation phrases
        'typing_phrase_2': 'AI 产品经理',
        'typing_phrase_3': '创造者与实践者',
        # Chatbot initial messages
        'chat_init_personal': '你好！我是周晶，很高兴认识你！你可以问我关于项目经历、技能背景等任何问题。',
        'chat_init_general': '你好！我是通用AI助手，你可以向我提任何问题。',
        # New project experiences from resume
        'project_momenta_title': 'Momenta',
        'project_momenta_subtitle': '基于多模态大模型的AI情绪音乐生成App',
        'project_momenta_date': '2026.01 - 至今',
        'project_momenta_role': '产品经理；AI工程师',
        'project_momenta_location': '香港',
        'project_momenta_badge': '预计3月上线App Store',
        'project_momenta_1': '产品规划与原型设计：基于深度用户访谈与竞品分析，制定产品Roadmap，定义MVP核心功能范围。使用Figma/Pencil完成iOS端全套UI/UX设计。',
        'project_momenta_2': '技术架构与工程落地：独立负责全栈iOS开发（Xcode + SwiftUI）。攻克了还原iOS 26液态玻璃（Liquid Glass）效果的技术难点——通过深入研究苹果官方开发者文档，定位到对应API接口，最终实现了流畅的原生级UI交互体验。',
        'project_momenta_3': '从0到1自主研究并接入Supabase云后端，实现了用户配置管理、数据云端同步及鉴权系统。独立完成Google登录和Apple ID登录的OAuth协议接入，体现了强执行力和自主解决问题的能力。',
        'project_momenta_4': 'AI模型应用：设计多模态（提示词工程）逻辑，调用OpenAI API进行语义与视觉分析，并接入Suno AI模型接口，融合HealthKit、WeatherKit等实现了从生理/环境数据到音乐生成的端到端自动化。',
        'project_momenta_5': '预计2026年3月上线App Store，目前处于最终开发与测试阶段。',
        'project_nanobanana_role': '联合创始人；产品运营',
        'project_nanobanana_date': '2025.09 - 至今',
        'project_nanobanana_1': '产品与功能迭代：主导6+项核心AI功能的产品设计与落地。独立完成从需求分析、页面逻辑设计到前端文案撰写的全流程。',
        'project_nanobanana_2': 'Prompt工程优化：深入优化底层提示词逻辑，显著提升生成图像的可控性与审美质量，通过精准调试解决了多项生成崩坏问题，大幅提升用户满意度。',
        'project_nanobanana_3': '增长运营与SEO战绩：制定并执行程序化SEO策略，核心功能页在Bing搜索排名第一，Google搜索排名前三，为网站带来了持续、免费的精准自然流量。页面总浏览量近80万。',
        'project_nanobanana_4': '全栈协作与提效：作为"懂技术的产品经理"，利用Python编写自动化脚本辅助竞品调研与关键词挖掘，结合数据分析结论，凝练出可落地商业场景的功能需求列表。',
        'project_nanobanana_5': '商业成果：平台已实现盈利，月收入约1万元，验证了AI图像生成垂直赛道的产品市场匹配度。',
        'project_loreal_title': '欧莱雅Brandstorm商赛',
        'project_loreal_subtitle': 'NFT驱动的美妆元宇宙战略',
        'project_loreal_date': '2022.01 - 2022.04',
        'project_loreal_role': '产品规划；UI设计师',
        'project_loreal_1': '主导构思并设计了一个Web3商业方案，旨在通过NFT技术为欧莱雅打造元宇宙社区，以提升年轻用户粘性与个性化体验。该方案在社交媒体推广中获得大量关注，成功带领团队晋级官方Mock-up Session。',
        'project_loreal_2': '负责核心产品策略与用户旅程设计：策划了"购买限定礼盒→获得并绑定专属NFT→消费积分升级NFT形象→跨界游戏联动"的完整商业闭环，并提出线上NFT形象与线下实体产品兑换的创新玩法。',
        'project_loreal_3': '作为团队设计师，独立完成了全套英文商业计划书（PPT）的撰写与视觉设计，设计了包括NFT会员系统、形象升级等关键环节的用户界面（UI）原型。',
        'project_mooncake_title': '"一期一礼"校园文创月饼项目',
        'project_mooncake_date': '2022.06 - 2022.10',
        'project_mooncake_role': '项目负责人',
        'project_mooncake_1': '作为总负责人，从0到1主导30人团队，统筹产品设计、供应链管理、营销及销售全案。最终售出1500套礼盒和500套礼袋，实现5万余元的项目净利润。',
        'project_mooncake_2': '搭建"线上小程序+350人社群+线下快闪"的整合营销矩阵，通过策划跨界直播、社群团购、社交裂变等活动，成功引爆校园市场，达成产品售罄。',
        'project_mooncake_3': '凭借项目商业价值与创新性，成功获得校创业中心等2个官方部门的联合支持，并得到共青团官方公众号"津彩青春"的专题报道，显著提升了品牌影响力。',
        # Campus experience
        'campus_arts_title': '文艺部干部',
        'campus_arts_org': '人文学院学生会',
        'campus_arts_date': '2020.09 - 2021.09',
        'campus_arts_1': '全流程统筹：主导新生文艺晚会、中西方文化节等4场大型校园活动的策划与落地，累计覆盖师生2000+人次。',
        'campus_arts_2': '幕后管理：负责舞台执行与调度，协调灯光、音响、道具等10余个技术环节，通过制定详细的《演职人员排期表》，确保节目衔接"零失误"。',
        # Skills section
        'skill_product_design': '产品设计与规划',
        'skill_product_design_desc': '熟练使用Figma、Sketch进行高保真原型设计；精通Xmind绘制业务流程图；具备规范的PRD文档撰写能力。',
        'skill_ai_tech': 'AI技术与应用',
        'skill_ai_tech_desc': '精通Prompt Engineering (Midjourney/SD/ChatGPT/Suno)；掌握Python (爬虫/数据清洗/NLP基础)；熟悉iOS Development (SwiftUI/Xcode) 及Supabase配置；了解SQL基础查询。',
        'skill_data_growth': '数据分析与增长',
        'skill_data_growth_desc': '擅长Programmatic SEO策略与落地；熟练运用Google Analytics (GA4) 进行流量分析；掌握A/B Testing实验方法；熟练使用Excel (透视表)、Tableau、SPSS进行数据分析。',
        'skill_tools': '通用工具',
        'skill_tools_desc': '熟练使用Notion、飞书多维表格进行项目管理；掌握Git/GitHub版本控制基础；具备PS、Pr、Ae音视频处理能力。',
        # Other info
        'other_language': '语言',
        'other_language_desc': '英语 IELTS:6.5；粤语',
        'other_hobbies': '兴趣爱好',
        'other_hobbies_desc': '羽毛球、摄影、胶片、徒步',
    }
}

