
PERSONAL_MODE_PROMPT = """你现在是周晶（Jing Zhou），目前香港理工大学研究生在读。请以第一人称回答用户的问题，展现出你的专业背景和个性。

个人背景信息：
- 教育背景：香港理工大学生成式AI硕士在读，新加坡国立大学交换优秀学者，本科天津财经大学广播电视学（财经新闻）专业，获2024届优秀毕业生、2022-2023国家奖学金
- 专业技能：拥有产品管理、AI技术、媒体设计三重技能（包括拍摄剪辑、影视制作、平面设计、新媒体运营等）
- 实习经验：
  1.产品实习生（AI产品组）：广州皮皮电子商务科技有限公司（2025.07-2025.09）。竞品分析（10个竞品，8万关键词），上线11个新功能（AI音乐/填色/纹身/翻译等），Prompt工程优化，SEO优化（88个专题页，35个外链，14篇成功文章，多语言），EDM营销，工作流优化。
  2.市场部实习生（新媒体/社区运营）：将门投资管理顾问（北京）有限公司（2023.04-2024.06）。负责2个公众号（150+技术文，50+公关文），运营知乎/B站/微博/CSDN/油管，策划节日热点/短视频。协助运营TechBeat AI社区（编辑380+文章，Talk全流程80+期，邀请20+大佬入驻）。
  3.新媒体营销实习生：网易游戏（2022.05-2022.07）。负责《决战！平安京》微博运营（发博1156篇，视频38个，涨粉2w），OPL职业联赛赛事宣发跟进（28场直播，112小时），策划营销事件（恩怨局、花式话题）。
  4.记者实习生：中山日报（2021.01-2021.03）。负责政法/三农/娱乐新闻采写，采访80+次，报道40+篇，4篇登“学习强国”（阅读15w+，单篇最高9w+）。
- 项目经验：
  1. AI音乐生成器 - 功能设计与prompt工程；SEO运营
  2. AI填色书 -  功能设计、prompt工程，bug修复；SEO运营；用户运营；
  3. AI纹身 - 功能设计
  4. 网页图片爬虫 - 数据驱动洞察
- 个人特质：结合技术AI专业知识与用户同理心，善于构建真正与用户产生共鸣的AI产品；执行力强（自己动手从0到1搭建个人网站）；b站、datacamp等公开平台自学代码。

详细信息页面导航：
- 完整简历页面：网站的 /resume 页面包含我的详细简历信息，包括教育背景、工作经历、技能和荣誉
- AI项目作品集：网站的 /ai-projects 页面展示我所有AI项目的详细案例，包括AI音乐生成器、AI填色书、AI纹身设计师等
- 创意作品集：网站的 /creative-works 页面展示我的媒体制作、影视、摄影和设计作品
- 关于我页面：网站的 /about 页面包含更多个人背景和故事

回答风格：
- 使用第一人称（我、我的）
- 保持专业但友好的语调
- 可以分享具体的项目经验和学习心得
- 展现对AI产品管理的热情和见解
- 适当展现个人成长历程和未来目标
- 当用户询问详细简历信息时，推荐他们查看"简历页面"获取完整信息
- 当用户想了解AI项目细节时，引导他们浏览"AI项目页面"查看详细案例
- 当用户对我的创意作品感兴趣时，建议他们访问"创意作品页面"
- 如果用户想了解更多个人故事，可以推荐"关于我页面"
- 我乐意引导用户探索网站的不同页面，发现更多我的专业能力和项目成果
- 只需要自然语言回答内容，不需要有任何解释语言，如："好的，现在我是周晶"，以及不要有"**"等符号

请记住，你就是周晶本人，以她的身份和经历来回答问题。当涉及详细信息时，引导用户浏览网站的相应页面获取更完整的信息。"""

# 多语言支持
translations = {
    'en': {
        'nav_home': 'Home',
        'nav_resume': 'Resume',
        'nav_ai_projects': 'AI Projects',
        'nav_creative_works': 'Creative Works',
        'hero_title': 'Zhou Jing 周晶',
        'hero_subtitle': 'AI Product Manager | Bridging Generative AI with User-Centric Narratives',
        'hero_tags_row1': ['MSc in GAH @PolyU', 'AI Product Intern', 'AI SaaS', 'SEO', 'Broadcasting & Television (Financial Journalism)', 'Micro Film', 'Director', 'Journalist', 'Multimedia Operations', 'Social Media Operations', 'Zhongshan Daily', 'NetEase Games'],
        'hero_tags_row2': ['National Scholarship', 'Outstanding Student of Tianjin', 'First-Class Scholarship', 'Outstanding Graduate', 'Outstanding League Member', 'National 2nd Prize in Micro Film Contest', 'Provincial 1st Prize in Advertising Contest', 'Badminton 🏸', 'Photography 📹', 'Swim 🏊‍♀️'],
        'hero_description': 'Leveraging my background in media communication and hands-on experience in AI product development, I build intuitive and engaging AI solutions that resonate with users.',
        'btn_view_projects': 'View My AI Projects',
        'btn_view_resume': 'View My Resume',
        'highlights_title': 'Key Achievements',
        'highlights_subtitle': 'Key milestones that demonstrate my commitment to excellence and innovation in AI product management.',
        'highlight_education': 'Top-Tier Education',
        'highlight_education_desc': 'The Hong Kong Polytechnic University (QS Ranking 54)',
        'highlight_ai_skills': 'AI Product Skills',
        'highlight_ai_skills_desc': 'Built 5+ AI products from zero coding background',
        'highlight_scholarship': 'National Scholarship',
        'highlight_scholarship_desc': 'Awarded to Top 1% of students nationwide',
        'highlight_competitions': '20+ Competition Honors',
        'highlight_competitions_desc': 'Including National 2nd Prize in Micro Film Contest, Provincial 1st Prize in Advertising Contest, and multiple entrepreneurship awards',
        'btn_view_resume': 'View My Resume',
        'ai_section_title': 'AI Assistant',
        'ai_section_subtitle': 'Chat with my AI-powered assistant to learn more about my background, projects, and skills.',
        'ai_chat_title': 'AI Assistant',
        'ai_status_online': 'Online & Ready to Help',
        'ai_welcome_message': 'Hi! I\'m Zhou Jing\'s AI assistant. Feel free to ask me about her projects, skills, experience, or anything else you\'d like to know!',
        'ai_chat_placeholder': 'Ask me about my projects or skills...',
        'chat_mode_label': 'Mode:',
        'chat_mode_personal': 'Personal Mode (About me)',
        'chat_mode_general': 'General Mode (Free chat)',
        'chat_model_label': 'AI Model:',
        'featured_projects_title': 'My AI Endeavors',
        'featured_projects_subtitle': 'Showcasing my journey in building AI products from concept to launch, with focus on user-centric design and technical innovation.',
        'skills_title': 'My Toolbox',
        'footer_contact': 'Get in Touch',
        'footer_copyright': '© 2025 Jing (Josic) Zhou',
        # Dropdown menu items
        'dropdown_all_projects': 'All Projects',
        'dropdown_musiccreator_ai': 'MusicCreator AI',
        'dropdown_coloringbook_ai': 'Coloringbook AI', 
        'dropdown_inker_ai': 'Inker.AI',
        'dropdown_web_picture_scraper': 'Web Picture Scraper',
        'dropdown_nanobanana_ai': 'NanoBanana AI',
        'dropdown_all_creative': 'All Creative Works',
        'dropdown_film_video': 'Film & Video',
        'dropdown_digital': 'Digital Interactive',
        'dropdown_photography': 'Photography',
        'dropdown_graphic': 'Graphic Design',
        # Resume page
        'resume_title': 'Resume',
        'resume_current_role': 'MSc in Generative AI @ PolyU | AI Product Manager',
        'resume_about_title': 'About Me',
        'resume_about_text': 'Jing is an aspiring AI Product Manager with a unique background in media communication and a Master\'s degree in Generative AI from The Hong Kong Polytechnic University. Her expertise lies in user-centric product design, prompt engineering, and leveraging data to drive product growth. She is passionate about creating intuitive AI applications that solve real-world problems.',
        'resume_experience_title': 'Internship Experience',
        'resume_education_title': 'Education',
        'resume_honors_title': 'Honors & Awards',
        'resume_projects_title': 'Publications & Projects',
        # Index page - view more projects button
        'view_more_projects': 'View More AI Projects',
        # Project descriptions on index page
        'project_musiccreator_desc': 'AI music generation platform, through product research, new feature development, prompt engineering and SEO optimization, to create an intuitive music creation experience.',
        'project_coloringbook_desc': 'AI coloring page generator, focused on user experience design, through new features, prompt engineering, SEO and bug fixes, providing a creative expression platform for all ages.',
        'project_inker_desc': 'AI tattoo design generator, responsible for new feature development, prompt engineering optimization and SEO strategy, helping users create personalized tattoo designs.',
        'project_webscraper_desc': 'Web image scraping tool, independently completed front-end, back-end, and deployment full-stack development, solving the pain point of low efficiency in image collection at work.',
        'project_nanobanana_desc': 'AI image generator, in a 3-person startup team, mainly responsible for feature research, development implementation, prompt engineering and SEO optimization.',
        # AI Projects page
        'ai_projects_page_title': 'AI Product Project Experience',
        'ai_projects_page_subtitle': 'From feature research to SEO optimization, deeply involved in the full-chain operation of AI products',
        'status_operating': 'Operating',
        'status_internship': 'Internship Project',
        'status_self_developed': 'Self-developed Tool',
        'total_traffic': 'Total Traffic',
        'daily_traffic': 'Daily Traffic',
        'monthly_visits': 'Monthly Visits',
        'conversion_3days': '3-Day Conversion',
        'bing_ranking': 'Bing Ranking',
        'google_ranking': 'Google Ranking',
        'time_saved_daily': 'Daily Time Saved',
        'internal_users': 'Internal Users',
        'view_details': 'View Details',
        'core_capabilities': 'Core Capabilities',
        'feature_research': 'Feature Research',
        'market_research': 'Market Research',
        'prompt_engineering': 'Prompt Engineering',
        'ai_output_optimization': 'AI Output Optimization',
        'seo_geo_optimization': 'SEO/GEO Optimization',
        'traffic_growth_strategy': 'Traffic Growth Strategy',
        'fullstack_development': 'Full-Stack Development',
        'tool_self_development': 'Tool Self-Development',
        'project_details': 'Project Details',
        'team_role': 'Team Role',
        'main_responsibilities': 'Main Responsibilities',
        'operating_status': 'Operating Status',
        'other_projects': 'Other Projects',
        # Creative Works page
        'creative_works_subtitle': 'A showcase of my media and design expertise',
        'portfolio_under_construction': 'Portfolio Under Construction',
        'portfolio_description': 'This creative portfolio showcasing my work in film, photography, graphic design, and digital interactive media will be available soon.',
        'preview_categories': 'Preview Categories',
        'film_video_title': 'Film & Video',
        'film_video_desc': 'Short films, documentaries, and video productions',
        'photography_title': 'Photography',
        'photography_desc': 'Portrait, landscape, and artistic photography',
        'graphic_design_title': 'Graphic Design',
        'graphic_design_desc': 'Posters, branding, and visual identity work',
        'digital_interactive_title': 'Digital Interactive',
        'digital_interactive_desc': 'AIGC images, SVG designs, and H5 pages',
        'back_to_home': 'Back to Home',
        'learn_about_me': 'Learn About Me',
        # Resume page - detailed content
        'internship_pipi_title': 'Product Intern, AI Product Group 2',
        'internship_pipi_company': 'Guangzhou Pipi E-Commerce Technology Co., Ltd',
        'internship_pipi_location': 'Guangzhou',
        'core_competencies_title': 'Core Competencies',
        'product_management': 'Product Management',
        'ai_technology': 'AI & Technology',
        'design_media': 'Design & Media',
        # Badge and Tag translations
        'badge_product_research': 'Product Research',
        'badge_feature_development': 'Feature Development',
        'badge_new_features': 'New Features',
        'badge_frontend_dev': 'Frontend Dev',
        'badge_backend_dev': 'Backend Dev',
        'badge_fullstack_deploy': 'Full-Stack Deploy',
        'badge_efficiency_tool': 'Efficiency Tool',
        'badge_bug_fix': 'Bug Fix',
        'badge_seo': 'SEO',
        'badge_feature_planning': 'Feature Planning',
        'badge_topic_page': 'Topic Page',
        # AI Projects page - detailed project info
        'nanobanana_subtitle': 'AI Image Generation & Editing Platform',
        'nanobanana_description': 'Collaborated with startup team, responsible for feature research, topic page planning, SEO/GEO optimization and full-chain product operations.',
        'musiccreator_subtitle': 'AI Music Generation Platform',
        'musiccreator_description': 'Responsible for product research, Prompt engineering and SEO optimization, promoting product feature iteration and traffic growth.',
        'coloringbook_subtitle': 'AI Coloring Page Generation Platform',
        'coloringbook_description': 'Responsible for feature research, Prompt engineering and SEO optimization, with core function pages ranking first in Google search.',
        'inker_subtitle': 'AI Tattoo Design Generation Platform',
        'inker_description': 'Responsible for feature research, Prompt engineering and SEO optimization, exploring AI application scenarios in niche markets.',
        'webscraper_subtitle': 'Batch Image Download Tool',
        'webscraper_description': 'Self-developed workflow optimization tool during internship, achieving automation of image batch downloading.',
        'stopped_operations': 'Stopped Operations',
        'bing_midi_editor': 'Bing MIDI Editor',
        # Resume page - Experience section titles and companies
        'intern_marketing': 'Marketing Intern, Marketing Department',
        'intern_product': 'Product Intern, AI Product Group 2',
        'intern_newmedia': 'New Media Marketing Intern, Marketing Department',
        'intern_journalist': 'Journalist Intern',
        'company_jiangmen': 'Jiangmen Investment Management Consultants (Beijing) Co., Ltd',
        'company_netease': 'NetEase Games',
        'company_zhongshan': 'Zhongshan Daily',
        'location_beijing': 'Beijing',
        'location_guangzhou': 'Guangzhou',
        'location_zhongshan': 'Zhongshan',
        # Education section
        'edu_msc_title': 'Master of Science in Generative AI',
        'edu_polyu': 'The Hong Kong Polytechnic University',
        'edu_polyu_desc': 'World Top 100 University',
        'edu_msc_desc': 'Specialized in Generative AI technologies, machine learning, and AI product development.',
        'edu_exchange_title': 'Exchange Scholar Program',
        'edu_nus': 'National University of Singapore',
        'edu_nus_desc': 'Fintech and Digital Business Course',
        'edu_exchange_desc': 'Award: Course Completion Certificate, Exchange Achievement Scholarship.',
        'edu_bachelor_title': 'Bachelor\'s Degree in Media Communication',
        'edu_tjufe': 'Tianjin University of Finance and Economics',
        'edu_bachelor_desc': 'Foundation in media production, digital communication, and user experience design.',
        # Honors section
        'honor_graduate': '2024 Outstanding graduate of Tianjin University of Finance and Economics',
        'honor_national_scholarship': '2022-2023 National Scholarship',
        'honor_tianjin_student': '2022-2023 Tianjin Outstanding Students',
        'honor_first_scholarship': '2020-2023 Tianjin University of Finance and Economics First-Class Scholarship',
        'honor_outstanding_student': '2020-2023 Outstanding Student of Tianjin University of Finance and Economics',
        # Projects section
        'projects_intro': 'For detailed case studies and project portfolios, please visit:',
        'projects_ai_portfolio': 'AI Projects Portfolio',
        'projects_creative_portfolio': 'Creative Works Portfolio',
        'projects_selected': 'Selected Projects',
        'project_ai_music': 'AI Music Generator Platform: End-to-end product development from user research to launch',
        'project_ai_coloring': 'AI Coloring Book Application: User-centric design and AI integration for creative tools',
        'project_python_tools': 'Python Web Scraping Tools: Data collection and analysis automation for product insights',
        'project_interactive': 'Interactive Media Projects: Award-winning digital storytelling and user experience design',
        # Core Competencies section
        'competency_user_research': 'User Research & Analysis',
        'competency_product_strategy': 'Product Strategy & Roadmapping',
        'competency_ab_testing': 'A/B Testing & Metrics',
        'competency_agile': 'Agile/Scrum Methodologies',
        'competency_leadership': 'Cross-functional Leadership',
        'competency_ml': 'Machine Learning Concepts',
        'competency_python': 'Python Programming',
        'competency_api': 'API Integration',
        'competency_data_analysis': 'Data Analysis & Visualization',
        'competency_video': 'Video Production',
        'competency_photography': 'Digital Photography',
        'competency_content': 'Content Strategy',
        'competency_seo': 'SEO Optimization',
        # AI Project detail pages - common labels
        'visit_product': 'Visit Product',
        'back_to_projects': 'Back to Project List',
        'project_overview': 'Project Overview',
        'responsible_content': 'Responsible Content & Feature Pages',
        'core_achievements': 'Core Achievements',
        'internship_role': 'Intern',
        'startup_member': 'Startup Team Member',
        'independent_developer': 'Independent Developer',
        'project_nature': 'Project Nature',
        'team_size': 'Team Size',
        'my_role': 'My Role',
        'tech_stack': 'Tech Stack',
        'application_scope': 'Application Scope',
        'core_tech': 'Core Technologies',
        'team_internal_use': 'Team Internal Use',
        'interested_in_fullstack': 'Interested in my full-stack development capabilities?',
        'explore_build_products': 'Let\'s explore how to build products that solve real problems from 0 to 1.',
        'view_resume': 'View My Resume',
        'view_more_projects_btn': 'View More Projects',
        'project_background': 'Project Background & Motivation',
        'solve_pain_points': 'Solving Work Pain Points',
        'fullstack_responsibilities': 'My Full-Stack Development Responsibilities',
        'tech_highlights': 'Technical Implementation Highlights',
        'frontend_ui': 'Frontend Interface & User Experience',
        'backend_crawler': 'Backend Crawler Technology',
        'performance_deploy': 'Performance Optimization & Deployment',
        'project_results': 'Project Results',
        'automation_download': 'Automated Download',
        'no_repetitive_work': 'No Repetitive Work',
        'tech_challenges': 'Technical Challenges & Solutions',
        'experience_summary': 'Experience Summary',
        'minutes': 'minutes',
        '30_minutes': '30 minutes',
        '4_orders': '4 Orders',
        # Resume Experience Section - Detailed descriptions
        'exp_pipi_1': 'SAAS competition research and analysis: Grab and analyze 10 AI total Competition article 80000 search keyword, refine the list of core functional requirements.',
        'exp_pipi_2': 'AI product function on-line and optimization: Design and develop 11 new features (contains AI music, AI coloring pages, AI tattoos, AI translations and more), compose function pages.',
        'exp_pipi_3': 'Optimize cue word engineering: Write the prompt words at the bottom of the function and fix the product Bug prompt words.',
        'exp_pipi_4': 'Perform SEO optimization: Execute programmatic SEO strategies to create 88 A special page; Build 35 outside the chain, success 14 article; Perform multilingual translation of website content.',
        'exp_pipi_5': 'EDM Marketing: A/B tests the content of the message and confirms the message sending policy. Send targeted advertising messages based on user billing status.',
        'exp_pipi_6': 'Workflow optimization: Use AI tools to optimize multiple workflows and save 1h of daily work time.',
        'exp_jiangmen_subtitle1': '1. New Media Operation',
        'exp_jiangmen_subtitle2': '2. Community Operation',
        'exp_jiangmen_platforms': '(Public Number, Zhihu, Station B, Microblog, CSDN, YouTube)',
        'exp_jiangmen_1': 'Responsible for editing, reviewing and operating 2 public numbers, publishing 150+ technical articles, 50+ brand public relations articles and 10+ activity articles. According to the account data to open a new column, enhance user stickiness, to achieve net account growth from negative to positive.',
        'exp_jiangmen_2': 'Responsible for the content update, review and maintenance of new media platforms (Zhihu, Station B, Weibo, CSDN, YouTube). Compared with before taking over, it insisted on the frequency of regular updates at least three times a week and the high activity of the platform.',
        'exp_jiangmen_3': 'Responsible for content planning and original content output, such as festival hot spot planning, short video planning and production, etc., with high interaction and reading volume.',
        'exp_jiangmen_4': 'Conduct monthly data analysis of new media matrix and complete visual report. Through analysis and targeted account optimization suggestions, the average completion rate increased by 15%.',
        'exp_jiangmen_community': '(TechBeat artificial intelligence community)',
        'exp_jiangmen_5': 'Assist in the operation of TechBeat artificial intelligence community, edit 380+ articles on typesetting technology, and be familiar with markdown and Latex formula editor. The whole process of Talk was completed and put on shelves for a total of 80+ periods.',
        'exp_jiangmen_6': 'Through Zhihu, Public Number, Twitter, csdn and Arxiv, we explored the interpretation of cutting-edge technical articles and pitch authors to enter the community, and successfully invited Daniel in the field of 20+ artificial intelligence to enter the community.',
        'exp_jiangmen_7': 'Assist to complete monthly community data report, skillfully use Growing io monitoring website for product analysis and customer acquisition analysis.',
        'exp_netease_1': 'The microblog account responsible for the decisive battle of Ping An Jing games @ decisive battle of Ping An Jing Youjiu sauce, independently planned and completed the production of pictures and texts and released 1156 articles, produced and released 38 videos (15s-1min), with a net increase of 2w fans.',
        'exp_netease_2': 'Follow up the preliminary marketing work and season publicity of OPL\'s decisive match of Ping An Jing Professional League in spring and summer. The specific task is to broadcast the match in real time, arrange the highlight moments after the match, and produce pictures and videos. A total of 28 live broadcasts were followed up for 112 hours, of which the single broadcast was about 4 hours, and the special broadcast would be extended to 6 hours.',
        'exp_netease_3': 'Participate in the planning of OPL marketing events, create hot topics and improve the degree of discussion: the hot topic event of "feud meeting" when OPL\'s two top teams meet in the season; The fancy topic event planned in the early stage of the finals.',
        'exp_zhongshan_1': 'As a reporter intern, he is responsible for collecting, writing and editing news, involving political news, legal news, three rural news, entertainment news and other sections.',
        'exp_zhongshan_2': 'Completed more than 80 interviews and more than 40 news reports. All articles were successfully published in Zhongshan Daily and Zhongshan "plus" APP.',
        'exp_zhongshan_3': 'Four of the articles were on the learning power at the same time, with a cumulative reading of 15W. The highest article, "The News on Agriculture, Countryside and Farmers Giving Play to Waste Heat, Zhongshan\'s Old Technician Helps New Variety Crops Smoothly" reached a reading volume of 91512 and praise volume of 5883.',
        # AI Project detail page descriptions
        'musiccreator_overview': 'MusicCreator AI is an AI music creation platform I participated in during my internship. I was mainly responsible for competitive research for different music styles and functional modules, Prompt engineering optimization, and SEO content construction for multiple core function pages.',
        'coloringbook_overview': 'Coloringbook AI is an AI coloring page generation platform I participated in during my internship. I was mainly responsible for market research of core functions, Prompt engineering optimization, and SEO content construction of related function pages, aiming to improve the natural search traffic of products.',
        'inker_overview': 'Inker.AI is an AI tattoo design platform I participated in during my internship. I was mainly responsible for market research, function planning, Prompt engineering optimization and SEO content construction of core function pages, helping users realize unique tattoo creativity through AI.',
        'nanobanana_overview': 'NanoBanana AI is a startup project I am currently operating. As a core member, I am mainly responsible for market research of new product functions, planning and writing of function topic pages, and SEO and GEO optimization strategies for different regions around the world, aiming to improve the search ranking and user conversion of products.',
        'webscraper_overview': 'Web Picture Scraper is a small self-developed tool I independently developed to optimize team workflow during my internship.',
        'responsible_pages': 'I was responsible for content planning and optimization of the following function pages:',
        'responsible_pages_nanobanana': 'I led the content construction and optimization of the following core function pages:',
        'achievement_result': 'Result:',
        'achievement_monthly_traffic': 'monthly traffic',
        'achievement_daily_traffic': 'daily traffic',
        'achievement_precise_traffic': 'precise monthly traffic',
        # MusicCreator AI feature descriptions
        'midi_editor_desc': 'Online MIDI editor.',
        'midi_editor_result': 'Result: This page ranks first in Bing search, and the keyword "midi" brings 1k monthly traffic.',
        'audio_to_midi_desc': 'Audio to MIDI converter tool.',
        'audio_to_midi_result': 'Result: The keyword "audio to midi" I wrote brings 940 precise monthly traffic.',
        'ai_mastering_desc': 'AI mastering',
        'text_to_music_desc': 'Text to music',
        'ai_singing_desc': 'AI singing voice generation',
        'ai_rap_desc': 'AI rap generation',
        'photo_to_music_desc': 'Photo to music',
        'lofi_converter_desc': 'Lofi music converter',
        'birthday_song_desc': 'Birthday song generator',
        'dubstep_maker_desc': 'Dubstep maker',
        # Coloringbook AI feature descriptions
        'coloring_book_desc': 'AI coloring book generator.',
        'coloring_book_result': 'Result: This feature ranks first in Google search and is the core feature that contributes the most revenue to the entire product.',
        'name_coloring_desc': 'Name coloring page generator, meeting users\' personalized customization needs.',
        # Inker.AI feature descriptions
        'birth_flower_tattoo_desc': 'Birth flower tattoo generator. Targeting the tattoo niche market, providing personalized tattoo design services combined with birth flower meanings.',
        # NanoBanana AI feature descriptions  
        'ai_image_combiner_desc': 'Intelligent image fusion tool.',
        'ai_image_combiner_result': 'Result: This page ranks first in Bing search results.',
        'floor_plan_desc': 'AI floor plan generation tool.',
        'floor_plan_result': 'Result: The function generated 4 paid conversions within 3 days of launch.',
        'cosplay_generator_desc': 'AI cosplay generator, focusing on the generation of anime and game characters.',
        'professional_photo_desc': 'AI professional photo generator, providing users with professional business portraits.',
        # Web Picture Scraper page content
        'webscraper_page_subtitle': 'Batch Image Download Tool - Self-developed workflow optimization tool during internship, achieving automation of image batch downloading.',
        'webscraper_overview_p1': 'Web Picture Scraper is a self-use tool I independently developed to optimize team workflow during my internship.',
        'webscraper_overview_p2': 'In daily work, I often need to find and download specific theme image materials. The traditional method of saving images one by one by right-clicking is extremely inefficient. Therefore, I developed this web image scraper tool. Just by entering a link, you can batch download images. This not only solved my own efficiency problems, but was also shared with colleagues. It saves team members an average of about 30 minutes of repetitive work time per day.',
        'webscraper_bg_title': 'Solving Work Pain Points',
        'webscraper_bg_p': 'In daily work, I often need to collect image materials from various websites for design and analysis. The traditional manual right-click save method is extremely inefficient, especially when facing web pages containing a large number of images.',
        'webscraper_bg_li1': 'Manual image saving is time-consuming and inefficient',
        'webscraper_bg_li2': 'Easy to miss hidden images on web pages',
        'webscraper_bg_li3': 'Unable to batch process multiple web pages',
        'webscraper_bg_li4': 'Lack of image classification and management functions',
        'webscraper_role_title': 'Independent Full-Stack Developer',
        'webscraper_role_li1': 'Requirements analysis and product design',
        'webscraper_role_li2': 'Frontend interface development and user experience design',
        'webscraper_role_li3': 'Backend API development and crawler logic implementation',
        'webscraper_role_li4': 'Database design and data management',
        'webscraper_role_li5': 'Cloud deployment and operations monitoring',
        'webscraper_tech_frontend': 'Frontend Interface & User Experience',
        'webscraper_tech_frontend_p': 'Designed a simple and intuitive user interface to ensure users can get started quickly.',
        'webscraper_tech_frontend_li1': 'Responsive design, supporting desktop and mobile access',
        'webscraper_tech_frontend_li2': 'Real-time progress display, users can see crawling progress',
        'webscraper_tech_frontend_li3': 'Image preview function, supporting batch selection and download',
        'webscraper_tech_frontend_li4': 'Error handling mechanism, friendly error messages',
        'webscraper_tech_backend': 'Backend Crawler Technology',
        'webscraper_tech_backend_p': 'Developed an efficient and stable web crawler system capable of intelligently identifying and crawling various types of images.',
        'webscraper_tech_backend_li1': 'Supports multiple image formats: JPG, PNG, GIF, WebP, etc.',
        'webscraper_tech_backend_li2': 'Smart deduplication algorithm to avoid downloading duplicate images',
        'webscraper_tech_backend_li3': 'Anti-crawler mechanism handling to ensure crawling stability',
        'webscraper_tech_backend_li4': 'Asynchronous processing architecture to improve crawling efficiency',
        'webscraper_tech_deploy': 'Performance Optimization & Deployment',
        'webscraper_tech_deploy_p': 'Comprehensive optimization for performance and user experience to ensure the practicality and stability of the tool.',
        'webscraper_tech_deploy_li1': 'Image compression and format conversion to reduce download size',
        'webscraper_tech_deploy_li2': 'CDN acceleration to improve global access speed',
        'webscraper_tech_deploy_li3': 'Fault tolerance mechanism to handle network exceptions and timeouts',
        'webscraper_tech_deploy_li4': 'Monitoring and alerting for real-time system operation status',
        'webscraper_challenge_title': 'Challenge: Anti-crawler Mechanism',
        'webscraper_challenge_p': 'Many websites have anti-crawler protection and need to simulate real user behavior',
        'webscraper_solution': 'Solution:',
        'webscraper_solution_1': 'Implemented User-Agent rotation, request delays and proxy pool mechanism',
        'webscraper_challenge2_title': 'Challenge: Image Format Compatibility',
        'webscraper_challenge2_p': 'Different websites use various image formats and encoding methods',
        'webscraper_solution_2': 'Developed a universal image detection and conversion algorithm',
        'webscraper_challenge3_title': 'Challenge: Cloud Deployment Cost',
        'webscraper_challenge3_p': 'Need to achieve stable cloud services within a limited budget',
        'webscraper_solution_3': 'Selected cost-effective Render platform and optimized resource usage',
        'webscraper_lesson1': 'Problem-oriented product thinking: Developing tools that truly solve problems starting from actual work pain points is more valuable than pursuing technical coolness.',
        'webscraper_lesson2': 'Full-stack development gains: Completing the entire project independently gave me a deep understanding of the full product development process and improved my comprehensive problem-solving ability.',
        'webscraper_lesson3': 'Importance of user experience: No matter how perfect the technical implementation is, if the user experience is poor, the product loses its value.',
        'webscraper_cta_title': 'Interested in my full-stack development capabilities?',
        'webscraper_cta_p': 'Let\'s explore how to build products from 0 to 1 that solve real problems.',
        'one_person': '1 person (Independent Development)',
        'internship_self_tool': 'Internship Self-developed Tool',
    },
    'zh': {
        'nav_home': '首页',
        'nav_resume': '简历',
        'nav_ai_projects': 'AI项目',
        'nav_creative_works': '创意作品',
        'hero_title': 'Zhou Jing 周晶',
        'hero_subtitle': 'AI产品经理 | 连接生成式AI与用户中心的叙事',
        'hero_tags_row1': ['香港理工大学GAH硕士', 'AI产品实习生', 'AI SaaS', 'SEO', '广播电视学（财经新闻）', '微电影','导演', '记者', '全媒体运营', '自媒体运营','中山日报', '网易游戏'],
        'hero_tags_row2': ['2022-2023国家奖学金', '2022-2023天津市优秀学生', '2020-2023校一等奖学金', '2024届优秀毕业生', '2020-2023天津财经大学优秀学生', '微电影大赛全国二等奖', '大广赛市级一等奖', '羽毛球 🏸', '摄影 📹', '游泳 🏊‍♀️'],
        'hero_description': '凭借我在媒体传播方面的背景和AI产品开发的实际经验，我构建直观且引人入胜的AI解决方案，与用户产生共鸣。',
        'btn_view_projects': '查看我的AI项目',
        'btn_view_resume': '查看我的简历',
        'highlights_title': '核心成就',
        'highlights_subtitle': '展现我在AI产品管理领域卓越和创新承诺的重要里程碑。',
        'highlight_education': '顶尖教育背景',
        'highlight_education_desc': '香港理工大学（QS排名54）',
        'highlight_ai_skills': 'AI产品技能',
        'highlight_ai_skills_desc': '0代码基础完成n+个AI产品',
        'highlight_scholarship': '国家奖学金',
        'highlight_scholarship_desc': '全国前1%学生获得',
        'highlight_competitions': '获得20+竞赛荣誉',
        'highlight_competitions_desc': '包括微电影大赛全国二等奖，大广赛市级一等奖，多项创业创新奖项等',
        'btn_view_resume': '查看我的简历',
        'ai_section_title': 'AI助手',
        'ai_section_subtitle': '与我的AI助手聊天，了解更多关于我的背景、项目和技能。',
        'ai_chat_title': 'AI助手',
        'ai_status_online': '在线并准备帮助',
        'ai_welcome_message': '您好！我是周晶的AI助手。请随时询问她的项目、技能、经验或任何您想了解的内容！',
        'ai_chat_placeholder': '询问我的项目或技能...',
        'chat_mode_label': '模式:',
        'chat_mode_personal': '个人模式 (About me)',
        'chat_mode_general': '通用模式 (自由对话)',
        'chat_model_label': 'AI模型:',
        'featured_projects_title': '我的AI探索',
        'featured_projects_subtitle': '展示我从概念到发布构建AI产品的旅程，专注于以用户为中心的设计和技术创新。',
        'skills_title': '我的工具箱',
        'footer_contact': '联系我',
        'footer_copyright': '© 2025 Zhou Jing 周晶',
        # Dropdown menu items
        'dropdown_all_projects': '所有项目',
        'dropdown_musiccreator_ai': 'MusicCreator AI',
        'dropdown_coloringbook_ai': 'Coloringbook AI',
        'dropdown_inker_ai': 'Inker.AI', 
        'dropdown_web_picture_scraper': 'Web Picture Scraper',
        'dropdown_nanobanana_ai': 'NanoBanana AI',
        'dropdown_all_creative': '所有创意作品',
        'dropdown_film_video': '影视作品',
        'dropdown_digital': '数字互动',
        'dropdown_photography': '摄影作品',
        'dropdown_graphic': '平面设计',
        # Resume page
        'resume_title': '简历',
        'resume_current_role': '香港理工大学生成式AI硕士 | AI产品经理',
        'resume_about_title': '关于我',
        'resume_about_text': '周晶是一位有抱负的AI产品经理，拥有独特的媒体传播背景和香港理工大学生成式AI硕士学位。她的专长在于以用户为中心的产品设计、提示工程和利用数据驱动产品增长。她热衷于创建解决现实问题的直观AI应用程序。',
        'resume_experience_title': '实习经历',
        'resume_education_title': '教育背景',
        'resume_honors_title': '荣誉奖项',
        'resume_projects_title': '项目作品',
        # Index page - view more projects button
        'view_more_projects': '查看更多AI项目',
        # Project descriptions on index page
        'project_musiccreator_desc': 'AI音乐生成器平台，通过产品调研、新增功能开发、prompt工程和SEO优化，打造直观的音乐创作体验。',
        'project_coloringbook_desc': 'AI填色页生成器，专注于用户体验设计，通过新增功能、prompt工程、SEO和bug修复，为所有年龄段用户提供创意表达平台。',
        'project_inker_desc': 'AI纹身设计生成器，负责新增功能开发、prompt工程优化和SEO策略，帮助用户创造个性化纹身设计。',
        'project_webscraper_desc': '网页图片抓取工具，独立完成前端、后端、部署全栈开发，解决工作中图片收集效率低的痛点问题。',
        'project_nanobanana_desc': 'AI图像生成器，在3人创业团队中主要负责功能调研、开发实现、prompt工程和SEO优化。',
        # AI Projects page
        'ai_projects_page_title': 'AI产品项目经验',
        'ai_projects_page_subtitle': '从功能调研到SEO优化，深度参与AI产品全链路运营',
        'status_operating': '运营中',
        'status_internship': '实习项目',
        'status_self_developed': '自研工具',
        'total_traffic': '总流量',
        'daily_traffic': '日均流量',
        'monthly_visits': '月访问量',
        'conversion_3days': '3天转化',
        'bing_ranking': 'Bing排名',
        'google_ranking': 'Google排名',
        'time_saved_daily': '日节省工时',
        'internal_users': '内部用户',
        'view_details': '查看详情',
        'core_capabilities': '核心能力',
        'feature_research': '功能调研',
        'market_research': '市场需求分析',
        'prompt_engineering': 'Prompt工程',
        'ai_output_optimization': 'AI输出优化',
        'seo_geo_optimization': 'SEO/GEO优化',
        'traffic_growth_strategy': '流量增长策略',
        'fullstack_development': '全栈开发',
        'tool_self_development': '工具自主开发',
        'project_details': '项目详情',
        'team_role': '团队角色',
        'main_responsibilities': '主要职责',
        'operating_status': '运营状态',
        'other_projects': '其他项目',
        # Creative Works page
        'creative_works_subtitle': '我的媒体与设计专业能力展示',
        'portfolio_under_construction': '作品集建设中',
        'portfolio_description': '这个创意作品集展示了我在影视、摄影、平面设计和数字互动媒体方面的作品，即将上线。',
        'preview_categories': '预览分类',
        'film_video_title': '影视作品',
        'film_video_desc': '短片、纪录片和视频制作',
        'photography_title': '摄影作品',
        'photography_desc': '人像、风景和艺术摄影',
        'graphic_design_title': '平面设计',
        'graphic_design_desc': '海报、品牌和视觉识别作品',
        'digital_interactive_title': '数字互动',
        'digital_interactive_desc': 'AIGC图像、SVG设计和H5页面',
        'back_to_home': '返回首页',
        'learn_about_me': '了解更多关于我',
        # Resume page - detailed content
        'internship_pipi_title': '产品实习生，AI产品组2',
        'internship_pipi_company': '广州皮皮电子商务科技有限公司',
        'internship_pipi_location': '广州',
        'core_competencies_title': '核心能力',
        'product_management': '产品管理',
        'ai_technology': 'AI与技术',
        'design_media': '设计与媒体',
        # Badge and Tag translations
        'badge_product_research': '产品调研',
        'badge_feature_development': '功能开发',
        'badge_new_features': '新增功能',
        'badge_frontend_dev': '前端开发',
        'badge_backend_dev': '后端开发',
        'badge_fullstack_deploy': '全栈部署',
        'badge_efficiency_tool': '效率工具',
        'badge_bug_fix': 'Bug修复',
        'badge_seo': 'SEO优化',
        'badge_feature_planning': '功能调研',
        'badge_topic_page': '专题页撰写',
        # AI Projects page - detailed project info
        'nanobanana_subtitle': 'AI图像生成与编辑平台',
        'nanobanana_description': '与创业团队合作，负责功能调研、专题页策划、SEO/GEO优化等全链路产品运营工作。',
        'musiccreator_subtitle': 'AI音乐生成平台',
        'musiccreator_description': '负责产品调研、Prompt工程及SEO优化，推动产品功能迭代与流量增长。',
        'coloringbook_subtitle': 'AI填色页生成平台',
        'coloringbook_description': '负责功能调研、Prompt工程及SEO优化，核心功能页Google搜索排名第一。',
        'inker_subtitle': 'AI纹身设计生成平台',
        'inker_description': '负责功能调研、Prompt工程及SEO优化，探索细分市场的AI应用场景。',
        'webscraper_subtitle': '图片批量下载工具',
        'webscraper_description': '实习期间自主开发的工作流优化工具，实现图片批量下载自动化。',
        'stopped_operations': '停止运营',
        'bing_midi_editor': 'Bing MIDI Editor',
        # Resume page - Experience section titles and companies
        'intern_marketing': '市场部实习生，市场部',
        'intern_product': '产品实习生，AI产品组2',
        'intern_newmedia': '新媒体营销实习生，市场部',
        'intern_journalist': '记者实习生',
        'company_jiangmen': '将门投资管理顾问（北京）有限公司',
        'company_netease': '网易游戏',
        'company_zhongshan': '中山日报',
        'location_beijing': '北京',
        'location_guangzhou': '广州',
        'location_zhongshan': '中山',
        # Education section
        'edu_msc_title': '生成式人工智能与人文科学理学硕士',
        'edu_polyu': '香港理工大学',
        'edu_polyu_desc': '世界前100名大学',
        'edu_msc_desc': '专注于生成式AI技术、机器学习和AI产品开发。',
        'edu_exchange_title': '交换学者项目',
        'edu_nus': '新加坡国立大学',
        'edu_nus_desc': '金融科技与数字商业课程',
        'edu_exchange_desc': '荣誉：课程结业证书、交换优秀奖学金。',
        'edu_bachelor_title': '广播电视学（财经新闻）',
        'edu_tjufe': '天津财经大学',
        'edu_bachelor_desc': '荣誉：国家奖学金、天津市优秀学生、思政微电影三等奖（国家级）、天津市大广赛一等奖（省级）AIGC论文研究：《AIGC在网络视频平台的应用现状与发展策略探析——以哔哩哔哩动画为例》',
        # Honors section
        'honor_graduate': '2024届天津财经大学优秀毕业生',
        'honor_national_scholarship': '2022-2023国家奖学金',
        'honor_tianjin_student': '2022-2023天津市优秀学生',
        'honor_first_scholarship': '2020-2023天津财经大学一等奖学金',
        'honor_outstanding_student': '2020-2023天津财经大学优秀学生',
        # Projects section
        'projects_intro': '详细案例研究和项目作品集，请访问：',
        'projects_ai_portfolio': 'AI项目作品集',
        'projects_creative_portfolio': '创意作品作品集',
        'projects_selected': '精选项目',
        'project_ai_music': 'AI音乐生成器平台：从用户研究到上线的端到端产品开发',
        'project_ai_coloring': 'AI填色书应用：以用户为中心的设计和AI集成创意工具',
        'project_python_tools': 'Python网页抓取工具：产品洞察的数据收集和分析自动化',
        'project_interactive': '互动媒体项目：获奖的数字故事讲述和用户体验设计',
        # Core Competencies section
        'competency_user_research': '用户研究与分析',
        'competency_product_strategy': '产品策略与路线图',
        'competency_ab_testing': 'A/B测试与指标',
        'competency_agile': '敏捷/Scrum方法论',
        'competency_leadership': '跨职能领导力',
        'competency_ml': '机器学习概念',
        'competency_python': 'Python编程',
        'competency_api': 'API集成',
        'competency_data_analysis': '数据分析与可视化',
        'competency_video': '视频制作',
        'competency_photography': '数字摄影',
        'competency_content': '内容策略',
        'competency_seo': 'SEO优化',
        # AI Project detail pages - common labels
        'visit_product': '访问产品',
        'back_to_projects': '返回项目列表',
        'project_overview': '项目概述',
        'responsible_content': '负责内容与功能页展示',
        'core_achievements': '核心成果',
        'internship_role': '实习生',
        'startup_member': '创业团队成员',
        'independent_developer': '独立开发者',
        'project_nature': '项目性质',
        'team_size': '团队规模',
        'my_role': '我的角色',
        'tech_stack': '技术栈',
        'application_scope': '应用范围',
        'core_tech': '核心技术',
        'team_internal_use': '团队内部使用',
        'interested_in_fullstack': '对我的全栈开发能力感兴趣？',
        'explore_build_products': '让我们探讨如何从0到1构建解决实际问题的产品。',
        'view_resume': '查看我的简历',
        'view_more_projects_btn': '查看更多项目',
        'project_background': '项目背景与动机',
        'solve_pain_points': '解决工作痛点',
        'fullstack_responsibilities': '我的全栈开发职责',
        'tech_highlights': '技术实现亮点',
        'frontend_ui': '前端界面与用户体验',
        'backend_crawler': '后端爬虫技术',
        'performance_deploy': '性能优化与部署',
        'project_results': '项目成果',
        'automation_download': '自动化下载',
        'no_repetitive_work': '重复劳动',
        'tech_challenges': '技术挑战与解决方案',
        'experience_summary': '经验总结',
        'minutes': '分钟',
        '30_minutes': '30分钟',
        '4_orders': '4单',
        # Resume Experience Section - Detailed descriptions
        'exp_pipi_1': 'SAAS竞品调研分析：抓取分析10个AI竞品共80000搜索关键词，提炼核心功能需求清单。',
        'exp_pipi_2': 'AI产品功能上线与优化：设计开发11个新功能（包含AI音乐、AI填色页、AI纹身、AI翻译等），撰写功能页面。',
        'exp_pipi_3': '优化提示词工程：编写功能底层prompt词，修复产品Bug提示词。',
        'exp_pipi_4': '执行SEO优化：执行程序化SEO策略创建88个专题页；建立35条外链，成功发文14篇；执行网站内容多语言翻译。',
        'exp_pipi_5': 'EDM营销：A/B测试消息内容，确定消息发送策略。根据用户计费状态发送针对性广告消息。',
        'exp_pipi_6': '工作流优化：使用AI工具优化多个工作流，节省每日1h工作时间。',
        'exp_jiangmen_subtitle1': '1. 新媒体运营',
        'exp_jiangmen_subtitle2': '2. 社区运营',
        'exp_jiangmen_platforms': '（公众号、知乎、B站、微博、CSDN、YouTube）',
        'exp_jiangmen_1': '负责2个公众号的编辑、审核和运营，发布150+篇技术文章、50+篇品牌公关文和10+篇活动文。根据账号数据开设新栏目，增强用户粘性，实现账号净增长从负到正。',
        'exp_jiangmen_2': '负责新媒体平台（知乎、B站、微博、CSDN、YouTube）的内容更新、审核和维护。相比接手前，坚持每周至少三次的定期更新频率和平台高活跃度。',
        'exp_jiangmen_3': '负责内容策划和原创内容输出，如节日热点策划、短视频策划制作等，互动量和阅读量高。',
        'exp_jiangmen_4': '进行新媒体矩阵月度数据分析并完成可视化报告。通过分析和针对性的账号优化建议，平均完成率提高15%。',
        'exp_jiangmen_community': '（TechBeat人工智能社区）',
        'exp_jiangmen_5': '协助运营TechBeat人工智能社区，编辑排版技术文章380+篇，熟悉markdown和Latex公式编辑器。全流程完成Talk并上架共80+期。',
        'exp_jiangmen_6': '通过知乎、公众号、Twitter、csdn和Arxiv，探索前沿技术文章解读并邀约作者入驻社区，成功邀请20+人工智能领域大牛入驻社区。',
        'exp_jiangmen_7': '协助完成社区月度数据报告，熟练使用Growing io监控网站进行产品分析和获客分析。',
        'exp_netease_1': '负责《决战！平安京》游戏的微博账号@决战平安京优酒酱，独立策划并完成图文制作发布1156篇，制作并发布38个视频（15s-1min），净增粉丝2w。',
        'exp_netease_2': '跟进OPL决战平安京职业联赛春夏赛季的前期营销工作和赛季宣传。具体任务为实时直播比赛、赛后整理高光时刻、制作图文视频。共跟进28场直播112小时，其中单场直播约4小时，特殊直播会延长至6小时。',
        'exp_netease_3': '参与OPL营销活动策划，制造热门话题提高讨论度：OPL赛季两支顶级战队相遇时的"宿敌会"热门话题事件；决赛前期策划的花式话题事件。',
        'exp_zhongshan_1': '作为记者实习生，负责新闻采集、撰写和编辑，涉及政治新闻、法律新闻、三农新闻、娱乐新闻等板块。',
        'exp_zhongshan_2': '完成80+次采访和40+篇新闻报道。所有文章均成功在中山日报和中山"加"APP上发表。',
        'exp_zhongshan_3': '其中4篇文章同时上了学习强国，累计阅读15W。最高文章《三农新闻发挥余热，中山老技术员帮助新品种作物顺利》达到阅读量91512和点赞量5883。',
        # AI Project detail page descriptions
        'musiccreator_overview': 'MusicCreator AI 是我在实习期间参与的一个AI音乐创作平台项目。我主要负责针对不同音乐风格和功能模块的竞品调研、Prompt工程优化，以及多个核心功能页面的SEO内容建设。',
        'coloringbook_overview': 'Coloringbook AI 是我在实习期间参与的一个AI填色页生成平台。我主要负责核心功能的市场调研、Prompt工程优化，以及相关功能页面的SEO内容建设，旨在提升产品的自然搜索流量。',
        'inker_overview': 'Inker.AI 是我在实习期间参与的一个AI纹身设计平台。我主要负责产品的市场调研、功能策划、Prompt工程优化以及核心功能页面的SEO内容建设，帮助用户通过AI实现独特的纹身创意。',
        'nanobanana_overview': 'NanoBanana AI 是一个我目前正在运营的创业项目。我作为核心成员，主要负责产品新功能的市场调研、功能专题页的策划与撰写，以及针对全球不同地区的SEO和GEO优化策略，旨在提升产品的搜索排名和用户转化。',
        'webscraper_overview': 'Web Picture Scraper是我在实习期间为优化团队工作流程而独立开发的一款自用小工具。',
        'responsible_pages': '我负责了以下功能页面的内容策划与优化：',
        'responsible_pages_nanobanana': '我主导了以下核心功能页面的内容建设与优化：',
        'achievement_result': '成果：',
        'achievement_monthly_traffic': '月流量',
        'achievement_daily_traffic': '日流量',
        'achievement_precise_traffic': '的精准月流量',
        # MusicCreator AI feature descriptions
        'midi_editor_desc': '在线MIDI编辑器。',
        'midi_editor_result': '成果：该页面Bing搜索排名第一，"midi"关键词带来1k月流量。',
        'audio_to_midi_desc': '音频转MIDI工具。',
        'audio_to_midi_result': '成果：我撰写的"audio to midi"关键词带来940的精准月流量。',
        'ai_mastering_desc': 'AI母带处理',
        'text_to_music_desc': '文本转音乐',
        'ai_singing_desc': 'AI歌声生成',
        'ai_rap_desc': 'AI说唱生成',
        'photo_to_music_desc': '图片转音乐',
        'lofi_converter_desc': 'Lofi音乐转换器',
        'birthday_song_desc': '生日歌生成器',
        'dubstep_maker_desc': 'Dubstep制作器',
        # Coloringbook AI feature descriptions
        'coloring_book_desc': 'AI填色书生成器。',
        'coloring_book_result': '成果：该功能在Google搜索排名第一，是整个产品收益贡献最大的核心功能。',
        'name_coloring_desc': '名字填色页生成器，满足用户的个性化定制需求。',
        # Inker.AI feature descriptions
        'birth_flower_tattoo_desc': '生日花纹身生成器。针对纹身细分市场，提供结合生日花语的个性化纹身设计服务。',
        # NanoBanana AI feature descriptions  
        'ai_image_combiner_desc': '智能图片融合工具。',
        'ai_image_combiner_result': '成果：该页面在Bing搜索结果中排名第一。',
        'floor_plan_desc': 'AI户型图生成工具。',
        'floor_plan_result': '成果：功能上线仅3天即产生4单付费转化。',
        'cosplay_generator_desc': 'AI角色扮演生成器，专注于二次元与游戏角色的生成。',
        'professional_photo_desc': 'AI职业形象照生成器，为用户提供专业的商务人像。',
        # Web Picture Scraper page content
        'webscraper_page_subtitle': '图片批量下载工具 - 实习期间自主开发的工作流优化工具，实现图片批量下载自动化。',
        'webscraper_overview_p1': 'Web Picture Scraper是我在实习期间为优化团队工作流程而独立开发的一款自用小工具。',
        'webscraper_overview_p2': '针对日常工作中需要频繁寻找和下载特定主题图片素材的痛点，传统的一次次右键保存方式效率极低。因此，我开发了这个网页图片爬虫工具，只需输入链接即可批量下载图片，不仅解决了自己的效率问题，也分享给同事使用，平均每天能为团队成员节省约30分钟的重复性工作时间。',
        'webscraper_bg_title': '解决工作痛点',
        'webscraper_bg_p': '在日常工作中，经常需要从各种网站收集图片素材用于设计和分析，传统的手动右键保存方式效率极低，特别是面对包含大量图片的网页时。',
        'webscraper_bg_li1': '手动保存图片耗时费力，效率低下',
        'webscraper_bg_li2': '容易遗漏网页中的隐藏图片',
        'webscraper_bg_li3': '无法批量处理多个网页',
        'webscraper_bg_li4': '缺乏图片分类和管理功能',
        'webscraper_role_title': '独立全栈开发者',
        'webscraper_role_li1': '需求分析和产品设计',
        'webscraper_role_li2': '前端界面开发和用户体验设计',
        'webscraper_role_li3': '后端API开发和爬虫逻辑实现',
        'webscraper_role_li4': '数据库设计和数据管理',
        'webscraper_role_li5': '云端部署和运维监控',
        'webscraper_tech_frontend': '前端界面与用户体验',
        'webscraper_tech_frontend_p': '设计了简洁直观的用户界面，确保用户能够快速上手使用。',
        'webscraper_tech_frontend_li1': '响应式设计，支持桌面和移动端访问',
        'webscraper_tech_frontend_li2': '实时进度显示，用户可以看到抓取进度',
        'webscraper_tech_frontend_li3': '图片预览功能，支持批量选择和下载',
        'webscraper_tech_frontend_li4': '错误处理机制，友好的错误提示信息',
        'webscraper_tech_backend': '后端爬虫技术',
        'webscraper_tech_backend_p': '开发了高效稳定的网页爬虫系统，能够智能识别和抓取各类图片。',
        'webscraper_tech_backend_li1': '支持多种图片格式：JPG、PNG、GIF、WebP等',
        'webscraper_tech_backend_li2': '智能去重算法，避免下载重复图片',
        'webscraper_tech_backend_li3': '反爬虫机制处理，确保抓取稳定性',
        'webscraper_tech_backend_li4': '异步处理架构，提升抓取效率',
        'webscraper_tech_deploy': '性能优化与部署',
        'webscraper_tech_deploy_p': '针对性能和用户体验进行了全面优化，确保工具的实用性和稳定性。',
        'webscraper_tech_deploy_li1': '图片压缩和格式转换，减少下载体积',
        'webscraper_tech_deploy_li2': 'CDN加速，提升全球访问速度',
        'webscraper_tech_deploy_li3': '容错机制，处理网络异常和超时',
        'webscraper_tech_deploy_li4': '监控告警，实时掌握系统运行状态',
        'webscraper_challenge_title': '挑战：反爬虫机制',
        'webscraper_challenge_p': '许多网站有反爬虫保护，需要模拟真实用户行为',
        'webscraper_solution': '解决方案：',
        'webscraper_solution_1': '实现了User-Agent轮换、请求延迟和代理池机制',
        'webscraper_challenge2_title': '挑战：图片格式兼容性',
        'webscraper_challenge2_p': '不同网站使用各种图片格式和编码方式',
        'webscraper_solution_2': '开发了通用的图片检测和转换算法',
        'webscraper_challenge3_title': '挑战：云端部署成本',
        'webscraper_challenge3_p': '需要在有限预算内实现稳定的云端服务',
        'webscraper_solution_3': '选择了性价比高的Render平台，优化了资源使用',
        'webscraper_lesson1': '问题导向的产品思维：从实际工作痛点出发，开发真正解决问题的工具比追求技术炫酷更有价值。',
        'webscraper_lesson2': '全栈开发的收获：独立完成整个项目让我深刻理解了产品开发的全流程，提升了解决问题的综合能力。',
        'webscraper_lesson3': '用户体验的重要性：技术实现再完美，如果用户体验不佳，产品就失去了价值。',
        'webscraper_cta_title': '对我的全栈开发能力感兴趣？',
        'webscraper_cta_p': '让我们探讨如何从0到1构建解决实际问题的产品。',
        'one_person': '1人（独立开发）',
        'internship_self_tool': '实习期间自研工具',
    }
}

